### ISSUE TITLE
Create-react-app 3 + Storybook + Typescript

### ISSUE THREAD

**Issue by jMoulis** [TypeStrong/ts-loader#1021]
### Expected Behaviour
Storybook to start with ts-loader
```javascript
const path = require('path');
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.tsx?$/,
    include: path.resolve(__dirname, '../src'),
    use: [
      require.resolve('ts-loader'),
      require.resolve('react-docgen-typescript-loader'),
    ],
  });
  config.resolve.extensions.push('.ts', '.tsx');
  return config;
};
```
### Actual Behaviour
Storybook starter complains about the fact that typescript emitted no output
```
ERROR in ./src/styles/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/julien/Documents/Sites/hedge-front/src/styles/index.ts.
    at makeSourceMapAndFinish (/Users/julien/Documents/Sites/hedge-front/node_modules/ts-loader/dist/index.js:80:15)
    at successLoader (/Users/julien/Documents/Sites/hedge-front/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/Users/julien/Documents/Sites/hedge-front/node_modules/ts-loader/dist/index.js:22:12)
 @ ./.storybook/config.js 4:0-45 16:12-24 23:11-16
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```
So I set `noEmit` to `false` in my tsconfig.json. Then it works. But, Create-React-App overwrite the noEmit key everytime I start cra server. I tested my story webpack config with `awesome-typescript-loader`and it works. I think maybe there is a conflict somewhere between noEmit et ts-loader?

### Steps to Reproduce the Problem
1- Install create-react-app v3 with typescript
2- Install storybook v5.1 react
3- install ts-loader
4- Install react-docgen-typescript-loader
5- Set the following in.storybook folder
```javascript
// webpack.config.js
const path = require('path');
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.tsx?$/,
    include: path.resolve(__dirname, '../src'),
    use: [
      require.resolve('ts-loader'),
      require.resolve('react-docgen-typescript-loader'),
    ],
  });
  config.resolve.extensions.push('.ts', '.tsx');
  return config;
};
```
```javascript
// config.js
import React from 'react';
import { configure, addDecorator, addParameters } from '@storybook/react';
import { theme, GlobalStyles } from 'styles';
import { ThemeProvider } from 'emotion-theming';
import { withInfo } from '@storybook/addon-info';
import { Global } from '@emotion/core';
import { withPropsTable } from 'storybook-addon-react-docgen';

const req = require.context('../src/components', true, /.stories.tsx$/);

addDecorator(withPropsTable);
function loadStories() {
  addDecorator(storyFn => (
    <>
      <Global styles={GlobalStyles} />
      <ThemeProvider theme={theme}>{storyFn()}</ThemeProvider>
    </>
  ));

  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);

```
6- Default tsconfig from create-react-app
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react",
    "noImplicitAny": false,
    "baseUrl": "./src",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noEmit": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/node_modules/*"]
}
```
7- Then toggle with `noEmit` key from `true` to `false`
### Location of a Minimal Repository that Demonstrates the Issue.
I'm sorry about not showing the repo, because it is private

**Comment by johnnyreilly** [comment]
Heya,

I'm sorry you're having difficulty. Without a reproducible repo it's going to be hard for someone to help I'm afraid.

It's worth saying that at my workplace we're using storybook with ts-loader without issue.

One thing that I'm a little curious about is that you're using ts-loader alongside create-react-app. CRA uses Babel under the bonnet, not ts-loader (though it uses our sister project of fork-ts-checker-webpack-plugin)

I don't know if that may be part of the puzzle?

**Comment by johnnyreilly** [comment]
Having reread what you've said, it seems the issue may lie with CRA forcing `noEmit: true` - is that right? It suggest that `awesome-typescript-loader` may internally always force that property to `false`. That could be worth investigating to see if that's the case.

`ts-loader` generally has a policy of trying to be drop in behaviour wise the same as `tsc`.

You may want to consider passing the `noEmit: false` config option via ts-loader options in your `webpack.config.js`. see https://github.com/TypeStrong/ts-loader/blob/master/README.md#compileroptions-object-default

**Comment by Bnaya** [comment]
CRA is using babel to transpile TypeScript,
i would advise to try and use the same setup with Storybook

**Comment by stringang** [comment]
@johnnyreilly  I also have the same problem, log output:
```
ERROR in ../src/client/main.ts
Module build failed (from ../node_modules/ts-loader/index.js):
Error: Debug Failure. False expression.
    at tryParsePattern (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:16675:18)
    at Object.matchPatternOrExact (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:16762:27)
    at tryLoadModuleUsingPaths (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:28007:33)
    at tryLoadModuleUsingPathsIfEligible (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:27514:20)
    at tryLoadModuleUsingOptionalResolutionSettings (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:27497:24)
    at tryResolve (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:27642:28)
    at C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:27634:69
    at Object.forEach (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:288:30)
    at nodeModuleNameResolverWorker (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:27634:25)
    at nodeModuleNameResolver (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:27627:16)
    at Object.resolveModuleName (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:27401:30)
    at C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\ts-loader\dist\servicesHost.js:411:57
    at resolveModule (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\ts-loader\dist\servicesHost.js:392:26)
    at moduleNames.map.moduleName (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\ts-loader\dist\servicesHost.js:98:63)
    at Array.map (<anonymous>)
    at Object.resolveModuleNames (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\ts-loader\dist\servicesHost.js:98:45)
    at Object.compilerHost.resolveModuleNames (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:125758:52)
    at resolveModuleNamesWorker (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:91519:127)
    at resolveModuleNamesReusingOldState (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:91765:24)
    at processImportedModules (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:93104:35)
    at findSourceFile (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:92905:17)
    at args (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:92751:85)
    at getSourceFileFromReferenceWorker (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:92718:34)
    at processSourceFile (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:92751:13)
    at processRootFile (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:92581:13)
    at C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:91597:60
    at Object.forEach (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:288:30)
    at Object.createProgram (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:91597:16)
    at synchronizeHostData (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:125778:26)
    at Object.getProgram (C:\Users\gang.liu\code\donews_node\ads-api-test-service\node_modules\typescript\lib\typescript.js:125870:13)
```
This is my code repository address：
https://github.com/stringang/typescript-vue-webpack-boilerplate

**Comment by johnnyreilly** [comment]
Thanks for sharing a repro @stringang - if someone could take a look at this it would be greatly appreciated. 🤗

**Comment by stringang** [comment]
I commented on the issue has been resolved, not ts-loader package cause, but my tsconfig.json configuration issues.

https://github.com/TypeStrong/ts-loader/issues/1021#issuecomment-552861882
