### ISSUE TITLE
Nesting tsconfig inside a subdirectory causes an error parsing even though tsc on it's own works fine.

### ISSUE THREAD

**Issue by afgriffiths** [TypeStrong/ts-loader#1043]
### Expected Behaviour
When nesting `tsconfig.json` inside a subdirectory of the project, `tsconfig.json` should be parsed without an error.

### Actual Behaviour
 An error occurs when trying to parse `tsconfig.json`. Here is the fill stack trace:

```
App threw an error during load
Error: Module build failed (from /home/adamfg/workplace/Boost/node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (/home/adamfg/workplace/Boost/node_modules/ts-loader/dist/index.js:19:18)
    at Object../src/main.ts (/home/adamfg/workplace/Boost/.webpack/main/index.js:97:7)
    at __webpack_require__ (/home/adamfg/workplace/Boost/.webpack/main/index.js:21:30)
    at /home/adamfg/workplace/Boost/.webpack/main/index.js:85:18
    at Object.<anonymous> (/home/adamfg/workplace/Boost/.webpack/main/index.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
```

### Steps to Reproduce the Problem
```
git clone --single-branch --branch backup/afgriffiths https://github.com/afgriffiths/Boost.git
git checkout 6b283fa8a1ab8b07c4dffddb9527183800dc5bde
npm install
npm start
```
If you then run the following commands:
```
cd cfg
tsc
```
you will see tsc executes without errors.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/afgriffiths/Boost/tree/backup/afgriffiths

This repository is simply a fork of this repository with some of the config files moved inside the `cfg` directory.

### Notes
This is **not** an issue with `ForkTsCheckerWebpackPlugin` please see [this almost identical issue](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/367) for confirmation.

**Comment by johnnyreilly** [comment]
Thanks for the detailed report; that's so helpful!

I'm afraid I can't look into this right now. If you'd like to investigate, I'd encourage it. I suspect this is a good starting point:

https://github.com/TypeStrong/ts-loader/blob/232babc0b1c3db579f3749a045982efcef5e03ae/src/config.ts#L97
