### ISSUE TITLE
Can't find package ts-loader@^3.5.3

### ISSUE THREAD

**Issue by NoDreaminger** [TypeStrong/ts-loader#1089]
### Expected Behaviour
A yo @pnp/spfx project

### Steps to Reproduce the Problem
Type and run 
`cnpm install`
I get this
`× Install fail! Error: [ts-loader@^3.5.3] Can't find package ts-loader@^3.5.3
Error: [ts-loader@^3.5.3] Can't find package ts-loader@^3.5.3
    at resolve (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:80:11)
    at resolve.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npminstall version: 3.27.0
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org ts-loader --save-dev`
Package.json:
`{
  "name": "file-management",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@pnp/spfx-property-controls": "1.14.0",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "vue": "^2.5.22",
    "vue-class-component": "^6.3.2",
    "vue-property-decorator": "^7.3.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "fork-ts-checker-webpack-plugin": "^0.5.2",
    "gulp": "~3.9.1",
    "gulp-sequence": "1.0.0",
    "sass-loader": "^7.1.0",
    "ts-loader": "^3.5.3",
    "vue-loader": "^15.6.2",
    "vue-template-compiler": "^2.5.22",
    "webpack-bundle-analyzer": "^3.0.3"
  }
}`

**Comment by NoDreaminger** [comment]
When i type:
`cnpm view ts-loader  versions`
show this：
`[ '0.1.0',
  '0.2.0',
  '0.2.1',
  '0.2.2',
  '0.2.3',
  '0.3.0',
  '0.3.1',
  '0.3.2',
  '0.3.3',
  '0.3.4',
  '0.4.0',
  '0.4.1',
  '0.4.2',
  '0.4.3',
  '0.4.4',
  '0.4.5',
  '0.4.6',
  '0.4.7',
  '0.5.0',
  '0.5.1',
  '0.5.2',
  '0.5.3',
  '0.5.4',
  '0.5.5',
  '0.5.6',
  '0.6.0',
  '0.6.1',
  '0.7.0',
  '0.7.1',
  '0.7.2',
  '0.8.0',
  '0.8.1',
  '0.8.2',
  '0.9.0',
  '0.9.1',
  '0.9.2',
  '0.9.3',
  '0.9.4',
  '0.9.5',
  '1.0.0-beta.1',
  '1.0.0',
  '1.1.0',
  '1.2.0',
  '1.2.1',
  '1.2.2',
  '1.3.0',
  '1.3.1',
  '1.3.2',
  '1.3.3',
  '2.0.0',
  '2.0.1',
  '2.0.2',
  '2.0.3',
  '2.1.0',
  '2.2.0',
  '2.2.1',
  '2.2.2',
  '2.3.0',
  '2.3.1',
  '2.3.2',
  '2.3.3',
  '2.3.4',
  '2.3.5',
  '2.3.6',
  '2.3.7',
  '3.0.2',
  '3.0.3',
  '3.0.4',
  '3.0.5',
  '3.1.0',
  '3.1.1',
  '3.2.0',
  '3.3.0',
  '3.3.1',
  '3.4.0',
  '3.5.0',
  '4.0.0-beta.0',
  '4.0.0',
  '4.0.1',
  '4.1.0',
  '4.2.0',
  '4.3.0',
  '4.3.1',
  '4.4.0',
  '4.4.1',
  '4.4.2',
  '4.5.0',
  '5.0.0',
  '5.1.0',
  '5.1.1',
  '5.2.0',
  '5.2.1',
  '5.2.2',
  '5.3.0',
  '5.3.1',
  '5.3.2',
  '5.3.3',
  '5.4.3',
  '5.4.4',
  '5.4.5',
  '6.0.0',
  '6.0.1',
  '6.0.2',
  '6.0.3',
  '6.0.4',
  '6.1.0',
  '6.1.1',
  '6.1.2',
  '6.2.0',
  '6.2.1',
  '6.2.2',
  '7.0.0' ]`
it doesn;t have @3.5.3.So i type and run
` cnpm install ts-loader@3.5.0 --save-dev`
show:
`√ Installed 1 packages
√ Linked 9 latest versions
√ Run 0 scripts
√ All packages installed (3 packages installed from npm registry, used 2s(network 1s), speed 74.96kB/s, json 10(42.67kB), tarball 69.55kB)`
It work.
