### ISSUE TITLE
TS-loader crash after deleting file

### ISSUE THREAD

**Issue by berickson1** [TypeStrong/ts-loader#1093]
Version: ts-loader@7.0.1

### Expected Behaviour
ts-loader does not crash

### Actual Behaviour
ts-loader crashes

### Steps to Reproduce the Problem
1) Create a file with a compiler error (in my case it wasn't included in the webpack bundle), run webpack configured with ts-loader in watcher mode
2) Delete the file
3) Observe

ERROR in ./src/start.tsx
Module build failed (from <myrepo>/node_modules/ts-loader/index.js):
TypeError: Cannot read property 'set' of undefined
    at doneWithAffectedFile (<myrepo>/node_modules/typescript/lib/typescript.js:101141:37)
    at toAffectedFileEmitResult (<myrepo>/node_modules/typescript/lib/typescript.js:101164:9)
    at emitNextAffectedFile (<myrepo>/node_modules/typescript/lib/typescript.js:101421:20)
    at Object.emit (<myrepo>/node_modules/typescript/lib/typescript.js:101450:49)
    at Object.emitFilesAndReportErrors (<myrepo>/node_modules/typescript/lib/typescript.js:102875:23)
    at emit (<myrepo>/node_modules/typescript/lib/typescript.js:104169:33)
    at executeSteps (<myrepo>/node_modules/typescript/lib/typescript.js:104290:25)
    at Object.done (<myrepo>/node_modules/typescript/lib/typescript.js:104110:13)
    at buildNextInvalidatedProject (<myrepo>/node_modules/typescript/lib/typescript.js:104868:32)
    at Object.buildReferences (<myrepo>/node_modules/ts-loader/dist/servicesHost.js:494:13)

**Comment by Zn4rK** [comment]
Can you downgrade to `7.0.0` to verify that it happens with version `7.0.1`? 

I'm not able to reproduce this...

**Comment by berickson1** [comment]
Yes I am using project references, but I'm struggling to reproduce this issue again (on 7.0.1 or 7.0.0).

**Comment by johnnyreilly** [comment]
I'm very interested in whether v7.0.1 has introduced any issues. Doesn't seem like this is evidence of that but it's good to keep an eye on. Thanks @Zn4rK for being on this too 🌻
