### ISSUE TITLE
Can't use ts-loader + typescript > 3.5.3 + aws-sdk

### ISSUE THREAD

**Issue by gvanderest** [TypeStrong/ts-loader#1099]
### Expected Behaviour

Attempting to webpack my project, I expect that unless I've got typings errors, should compile-- or at least return those typings errors.

### Actual Behaviour

An error message from typescript attempting to compile via ts-loader: `Error: Debug Failure. False expression.`

I'm only able to use TypeScript <= 3.5.3, but have attempted with each release .. even 3.9.0 and 4.0.0 builds.

### Steps to Reproduce the Problem

1. Create a project with ts-loader, typescript > 3.5.3, and aws-sdk S3 client
2. Try to build via webpack

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/gvanderest/ts-loader-aws-sdk-issue

Instructions in the README.

### Error Message

```
ERROR in ./node_modules/aws-sdk/lib/event-stream/event-message-chunker-stream.js
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. False expression.
    at getConstructorDefinedThisAssignmentTypes (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:40859:22)
    at getWidenedTypeForAssignmentDeclaration (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:40734:63)
    at getTypeOfVariableOrParameterOrPropertyWorker (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:41067:24)
    at getTypeOfVariableOrParameterOrProperty (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:41015:28)
    at getTypeOfSymbol (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:41339:24)
    at checkPropertyAccessExpressionOrQualifiedName (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:55698:53)
    at checkPropertyAccessExpression (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:55557:17)
    at checkExpressionWorker (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:60102:28)
    at checkExpression (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:60023:38)
    at checkPrefixUnaryExpression (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:58791:31)
    at checkExpressionWorker (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:60139:28)
    at checkExpression (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:60023:38)
    at checkTruthinessExpression (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:62523:42)
    at checkIfStatement (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:62454:24)
    at checkSourceElementWorker (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:64920:28)
    at checkSourceElement (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:64800:17)
    at Object.forEach (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:317:30)
    at checkBlock (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:62090:20)
    at checkSourceElementWorker (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:64914:28)
    at checkSourceElement (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:64800:17)
    at checkWhileStatement (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:62514:13)
    at checkSourceElementWorker (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:64924:28)
    at checkSourceElement (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:64800:17)
    at Object.forEach (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:317:30)
    at checkBlock (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:62086:20)
    at checkSourceElementWorker (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:64914:28)
    at checkSourceElement (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:64800:17)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:58581:21)
    at checkDeferredNode (/Volumes/workplace/ts-loader-aws-sdk-error/node_modules/typescript/lib/typescript.js:65071:21)
    at Map.forEach (<anonymous>)
 @ ./node_modules/aws-sdk/lib/event-stream/streaming-create-event-stream.js 8:32-87
 @ ./node_modules/aws-sdk/lib/node_loader.js
 @ ./node_modules/aws-sdk/clients/s3.js
 @ ./index.ts
```

**Comment by vaskevich** [comment]
I have the same issue with `aws-next`. The issue appears to be within [`event-message-chunker-stream.js`](https://github.com/aws/aws-sdk-js/blob/master/lib/event-stream/event-message-chunker-stream.js).

**Comment by rcoundon** [comment]
Did you ever find a workaround or solution for this?

**Comment by OlenDavis** [comment]
Considering the error happens because the `ts.Debug.assert(types.length === declarations.length);` assertion fails here:
```js
function getConstructorDefinedThisAssignmentTypes(types, declarations) {
    ts.Debug.assert(types.length === declarations.length);
    return types.filter(function (_, i) {
        var declaration = declarations[i];
        var expression = ts.isBinaryExpression(declaration) ? declaration :
            ts.isBinaryExpression(declaration.parent) ? declaration.parent : undefined;
        return expression && isDeclarationInConstructor(expression);
    });
}
```
And the `Transform` constructor takes an optional `options` argument, but the `EventMessageChunkerStream` class [they're declaring here](https://github.com/aws/aws-sdk-js/blob/master/lib/event-stream/event-message-chunker-stream.js#L6) takes a non-optional `options` argument:
```ts
/** @type {Transform} */
function EventMessageChunkerStream(options) {
    Transform.call(this, options);
```
Even though [they're and making `EventMessageChunkerStream` extend the `Transform` constructor here](https://github.com/aws/aws-sdk-js/blob/master/lib/event-stream/event-message-chunker-stream.js#L18):
```ts
EventMessageChunkerStream.prototype = Object.create(Transform.prototype);
```

Could that be the culprit? I.e. basically Typescript used to (pre 3.5.3) not be sophisticated enough to notice the mismatch in optional args, but now it does, so the `aws-sdk` authors would need to mark the `options` argument to be optional?

Regardless, this would suggest this isn't a `ts-loader` issue but an `aws-sdk` issue.

**Comment by gvanderest** [comment]
Quite possible, but I wonder if that explains why it only fails when going
through ts-loader, and not during a typescript build/compile?

**Comment by gvanderest** [comment]
That sounds quite possible.  Thanks for digging!

**Comment by OlenDavis** [comment]
FYI from the corresponding issue I created in the `aws-sdk-js` repo: https://github.com/aws/aws-sdk-js/issues/3390#issuecomment-681189564
