### ISSUE TITLE
Inheritance TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by peni4142** [TypeStrong/ts-loader#1107]
Hi
I think that is a bug. The class `Property` is working fine, but the class `Method` for any reason not. It seems to be pretty much the same code. If I do not use the `constructor` of `Method`, the code works

```json
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react-dom": "^16.9.0",
    "mocha": "^7.1.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "ts-mockito": "^2.5.0",
    "typescript": "~3.7.2"
  },
  "devDependencies": {
    "@types/mocha": "^7.0.2",
    "@types/react": "^16.9.35",
    "ts-loader": "^7.0.4",
    "ts-node": "^8.10.1"
  }
```

```ts
import { MemberType } from "./MemberType";
import { Property } from "./Property";
import { Method } from "./Method";

export class Member {

    protected constructor(public MemberType: MemberType, public Name: string, public ReturnType: string, public Static: boolean = false) { }

    public static ParseFromString(s: string): Member {
        if (s.includes("(")) {
            return this.parseMethodFromString(s);
        } else {
            return this.parsePropertyFromString(s);
        }
    }

    private static parseMethodFromString(s: string): Method {
        let match: RegExpExecArray | null = /\s*([\w\d]+)\s*:\s*([\w\d]+)/.exec(s);
        if (match === null) {
            throw new Error("Could not match \"" + s + "\"");
        }
        return new Method(match[1], match[2]);
    }

    private static parsePropertyFromString(s: string): Property {
        let match: RegExpExecArray | null = /\s*([\w\d]+)\s*:\s*([\w\d]+)/.exec(s);
        if (match === null) {
            throw new Error("Could not match \"" + s + "\"");
        }
        return new Property(match[1], match[2]);
    }

}
```
```ts
import { Member } from "./Member";
import { MemberType } from "./MemberType";

export class Method extends Member {
    constructor(Name: string, ReturnType: string, Static: boolean= false) {
        super(MemberType.Method, Name, ReturnType, Static);
    }
}
```
```ts
import { Member } from "./Member";
import { MemberType } from "./MemberType";


export class Property extends Member {
    constructor(Name: string, ReturnType: string, Static: boolean= false) {
        super(MemberType.Property, Name, ReturnType, Static);
    }
}
```

```ts
import { Member } from "./Member";
import { MemberType } from "./MemberType";

export class Method extends Member {
    constructor(Name: string, ReturnType: string, Static: boolean= false) {
        super(MemberType.Method, Name, ReturnType, Static);
    }
}
```
```ts
export enum MemberType {
    Method,
    Property
}
```

```
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at extendStatics (c:\diagram\src\logic\Method.ts:7:16)
    at __extends (c:\diagram\src\logic\Method.ts:10:9)
    at c:\diagram\src\logic\Method.ts:19:5
    at Object.<anonymous> (c:\diagram\src\logic\Method.ts:25:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (c:\diagram\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (c:\diagram\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
```

**Comment by peni4142** [comment]
Ok, maybe it is just a circle problem. Sry :)
