### ISSUE TITLE
Webpack 5: deprecation warning [DEP_WEBPACK_MODULE_ERRORS] 

### ISSUE THREAD

**Issue by sanex3339** [TypeStrong/ts-loader#1194]
### Expected Behaviour
No deprecation warning

### Actual Behaviour
```
(node:69430) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
```

### Steps to Reproduce the Problem
PR with the error:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/776

Full trace:
```
(node:69499) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
    at Object.reportTranspileErrors (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/ts-loader/dist/instances.js:263:24)
    at successLoader (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/ts-loader/dist/index.js:28:17)
    at Object.loader (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/ts-loader/dist/index.js:24:5)
    at LOADER_EXECUTION (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at Array.<anonymous> (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/loader-runner/lib/LoaderRunner.js:224:4)
    at runCallbacks (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:24:49)
    at /Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:194:4
    at /Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:123:16
```

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/776

**Comment by johnnyreilly** [comment]
Thanks for the report @sanex3339 - if you'd like to submit a PR to resolve this we'd be very grateful.

In terms of support, `ts-loader` aims to continue supporting webpack 4 and 5 for now, (just as we've supported multiple versions of webpack in the past). So any patch should support webpack 4 and webpack 5.

You can see a feature testing approach in the codebase that does this here: https://github.com/TypeStrong/ts-loader/blob/master/src/after-compile.ts#L253

Feel free to reach out for help - particularly when it comes to the tests; we're happy to collaborate on PRs ❤️🌻

**Comment by allen-munsch** [comment]
```
yarn add ts-loader@8.0.5
```

- https://github.com/TypeStrong/ts-loader/pull/1195

Worked for me using ^5.52.0
