### ISSUE TITLE
Builds fail when using thread-loader

### ISSUE THREAD

**Issue by valerio** [TypeStrong/ts-loader#1206]
### Expected Behaviour

Using `thread-loader` before `ts-loader`, compilation of a project should succeed.

### Actual Behaviour

Compilation fails with the following error:
```
[webpack-cli] Compilation finished
assets by status 655 bytes [cached] 1 asset
./src/app.ts 39 bytes [built] [code generated] [1 error]

ERROR in ./src/app.ts
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Invalid value used as weak map key
    at PoolWorker.fromErrorObj (/Users/valeriopipolo/repos/tsloaderleak/node_modules/thread-loader/dist/WorkerPool.js:344:12)
    at /Users/valeriopipolo/repos/tsloaderleak/node_modules/thread-loader/dist/WorkerPool.js:217:29
    at WeakMap.set (<anonymous>)
    at Object.getTypeScriptInstance (/Users/valeriopipolo/repos/tsloaderleak/node_modules/ts-loader/dist/instances.js:37:23)
    at Object.loader (/Users/valeriopipolo/repos/tsloaderleak/node_modules/ts-loader/dist/index.js:16:41)

webpack 5.3.2 compiled with 1 error in 441 ms
```

### Steps to Reproduce the Problem

Use a minimal webpack configuration as follows:
```js
module.exports = {
  devtool: "inline-source-map",
  entry: "./src/app.ts",
  output: {
    filename: "bundle.js",
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: ["thread-loader", "ts-loader"],
      },
    ],
  },
};
```

Running builds with `webpack` should fail.
Reproducible with the following dependencies:
```
    "thread-loader": "3.0.1",
    "ts-loader": "8.0.8",
    "typescript": "4.0.5",
    "webpack": "4.13.0"
```

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/valerio/tsloader-build-issue-with-thread-loader

**Comment by valerio** [comment]
When using `thread-loader` the `loader._compiler` instance is set to undefined, which makes setting it as a key to a `WeakMap` fail at runtime: https://github.com/TypeStrong/ts-loader/blob/master/src/instances.ts#L63

A couple ideas for workarounds:
- use a "marker" object to use as a key in the `WeakMap` whenever a webpack compiler isn't available passed
- keep a separate "fallback" map of instance name -> TS compiler that should be used only when the webpack compiler is undefined

I'll see which one seems nicer and make a PR for it.

**Comment by johnnyreilly** [comment]
Thanks @valerio!

**Comment by valerio** [comment]
I've updated the version of webpack in the first post to `4.12.2`.

With the fix I had in mind compilation will work fine up to that version, but using webpack >= 4.13.0 will fail with a different error:
```
ERROR in ./src/app.ts
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'hooks' of undefined
    at PoolWorker.fromErrorObj (/Users/valeriopipolo/repos/tsloader-build-issue-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:344:12)
    at /Users/valeriopipolo/repos/tsloader-build-issue-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:217:29
    at mapSeries (/Users/valeriopipolo/repos/tsloader-build-issue-with-thread-loader/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/Users/valeriopipolo/repos/tsloader-build-issue-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:171:34)
    at Object.initializeInstance (/Users/valeriopipolo/repos/ts-loader/dist/instances.js:267:31)
    at successLoader (/Users/valeriopipolo/repos/ts-loader/dist/index.js:26:17)
    at Object.loader (/Users/valeriopipolo/repos/ts-loader/dist/index.js:23:5)
```

This happens also with lower versions of `ts-loader` such as 8.0.7, so it seems like a separate issue.

**Comment by Krasnopir** [comment]
i freezed my version of ts-loader on "8.0.7" instead "^8.0.7" and all work.

**Comment by johnnyreilly** [comment]
v8.0.9 is should be out in the next 20 minutes and will hopefully resolve the issues https://github.com/TypeStrong/ts-loader/releases/tag/v8.0.9

**Comment by Krasnopir** [comment]
@johnnyreilly 8.0.9 work without errors. Thanks a lot!

**Comment by johnnyreilly** [comment]
Thanks @valerio for fixing and @Krasnopir for testing! ❤️🌻

**Comment by caseyjhol** [comment]
> I've updated the version of webpack in the first post to `4.12.2`.
> 
> With the fix I had in mind compilation will work fine up to that version, but using webpack >= 4.13.0 will fail with a different error:
> 
> ```
> ERROR in ./src/app.ts
> Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
> Thread Loader (Worker 0)
> Cannot read property 'hooks' of undefined
>     at PoolWorker.fromErrorObj (/Users/valeriopipolo/repos/tsloader-build-issue-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:344:12)
>     at /Users/valeriopipolo/repos/tsloader-build-issue-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:217:29
>     at mapSeries (/Users/valeriopipolo/repos/tsloader-build-issue-with-thread-loader/node_modules/neo-async/async.js:3625:14)
>     at PoolWorker.onWorkerMessage (/Users/valeriopipolo/repos/tsloader-build-issue-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:171:34)
>     at Object.initializeInstance (/Users/valeriopipolo/repos/ts-loader/dist/instances.js:267:31)
>     at successLoader (/Users/valeriopipolo/repos/ts-loader/dist/index.js:26:17)
>     at Object.loader (/Users/valeriopipolo/repos/ts-loader/dist/index.js:23:5)
> ```
> 
> This happens also with lower versions of `ts-loader` such as 8.0.7, so it seems like a separate issue.

I'm running into this exact same `Cannot read property 'hooks' of undefined` error with ts-loader v8.0.11, thread-loader v3.0.1, and webpack v4.44.2.

**Comment by MohammedAliMohammedElsady** [comment]
versions -> "thread-loader": "^4.0.4",
                   "ts-loader": "^9.5.1"

how solve this error.

ERROR in ./src/views/CRUD/utils.tsx
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):     
Thread Loader (Worker 5)
D:\NewArt\superset\superset-master\superset-frontend\src\views\CRUD\utils.tsx: Cannot read properties of undefined (reading 'has')

    at resolvePath (D:\NewArt\superset\superset-master\superset-frontend\node_modules\babel-plugin-lodash\lib\importModule.js:22:24)
    at importModule (D:\NewArt\superset\superset-master\superset-frontend\node_modules\babel-plugin-lodash\lib\importModule.js:36:53)
    at memoized (D:\NewArt\superset\superset-master\superset-frontend\node_modules\lodash\memoize.js:62:23)
    at D:\NewArt\superset\superset-master\superset-frontend\node_modules\babel-plugin-lodash\lib\index.js:203:62
    at arrayEach (D:\NewArt\superset\superset-master\superset-frontend\node_modules\lodash\_arrayEach.js:15:9)
    at forEach (D:\NewArt\superset\superset-master\superset-frontend\node_modules\lodash\forEach.js:38:10)
    at D:\NewArt\superset\superset-master\superset-frontend\node_modules\babel-plugin-lodash\lib\index.js:193:30
    at arrayEach (D:\NewArt\superset\superset-master\superset-frontend\node_modules\lodash\_arrayEach.js:15:9)
    at forEach (D:\NewArt\superset\superset-master\superset-frontend\node_modules\lodash\forEach.js:38:10)
    at D:\NewArt\superset\superset-master\superset-frontend\node_modules\babel-plugin-lodash\lib\index.js:181:28
    at arrayEach (D:\NewArt\superset\superset-master\superset-frontend\node_modules\lodash\_arrayEach.js:15:9)
    at forEach (D:\NewArt\superset\superset-master\superset-frontend\node_modules\lodash\forEach.js:38:10)
    at PluginPass.Program (D:\NewArt\superset\superset-master\superset-frontend\node_modules\babel-plugin-lodash\lib\index.js:170:26)
    at newFn (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\visitors.js:172:14)
    at NodePath._call (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\path\context.js:49:20)
    at NodePath.call (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\path\context.js:39:18)
    at NodePath.visit (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\path\context.js:88:31)
    at TraversalContext.visitQueue (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\context.js:90:16)       
    at TraversalContext.visitSingle (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\context.js:66:19)      
    at TraversalContext.visit (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\context.js:113:19)
    at traverseNode (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at traverse (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\traverse\lib\index.js:53:34)
    at transformFile (D:\NewArt\superset\superset-master\superset-frontend\node_modules\@babel\core\lib\transformation\index.js:80:31)
    at transform.next (<anonymous>)
    at step (D:\NewArt\superset\superset-master\superset-frontend\node_modules\gensync\index.js:261:32)
    at D:\NewArt\superset\superset-master\superset-frontend\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (D:\NewArt\superset\superset-master\superset-frontend\node_modules\gensync\index.js:223:11)
