### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xclidongbo** [TypeStrong/ts-loader#1272]
ERROR in ./src/index.tsx
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/lidongbo/WorkBentch/React/reactadmin/src/index.tsx.
    at makeSourceMapAndFinish (/Users/lidongbo/WorkBentch/React/reactadmin/node_modules/ts-loader/dist/index.js:53:18)
    at successLoader (/Users/lidongbo/WorkBentch/React/reactadmin/node_modules/ts-loader/dist/index.js:40:5)
    at Object.loader (/Users/lidongbo/WorkBentch/React/reactadmin/node_modules/ts-loader/dist/index.js:23:5)

**Comment by kulkarnipradnyas** [comment]
did you get any solution?i facing same issue.
