### ISSUE TITLE
Issue using thread-loader with ts-loader

### ISSUE THREAD

**Issue by 0xdeafcafe** [TypeStrong/ts-loader#1281]
### Expected Behaviour

The build succeeds, and in a v short amount of time 🏃.

### Actual Behaviour

When running with thead-loader, the following error is outputted:

```bash
assets by status 1.4 KiB [cached] 2 assets
./src/index.tsx 39 bytes [built] [1 error]

ERROR in ./src/index.tsx
Module build failed (from ../../../node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'options' of undefined
    at PoolWorker.fromErrorObj (/Users/afr/Source/cuvva/monorepo/js/react/node_modules/thread-loader/dist/WorkerPool.js:346:12)
    at /Users/afr/Source/cuvva/monorepo/js/react/node_modules/thread-loader/dist/WorkerPool.js:219:29
    at mapSeries (/Users/afr/Source/cuvva/monorepo/js/react/node_modules/neo-async/async.js:3625:14)
    at makeResolversAndModuleResolutionHost (/Users/afr/Source/cuvva/monorepo/js/react/node_modules/ts-loader/dist/servicesHost.js:22:34)
    at Object.makeSolutionBuilderHost (/Users/afr/Source/cuvva/monorepo/js/react/node_modules/ts-loader/dist/servicesHost.js:348:91)
    at Object.buildSolutionReferences (/Users/afr/Source/cuvva/monorepo/js/react/node_modules/ts-loader/dist/instances.js:338:55)
    at Object.loader (/Users/afr/Source/cuvva/monorepo/js/react/node_modules/ts-loader/dist/index.js:22:17)
```

### Steps to Reproduce the Problem

Create a TS project using webpack, this is the config I have gone with

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const CopyPlugin = require('copy-webpack-plugin');
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');
const os = require('os');
/* eslint-enable @typescript-eslint/no-var-requires */

module.exports = {
	entry: './src/index.tsx',
	resolve: {
		extensions: ['.ts', '.tsx', '.js'],
		plugins: [
			new TsconfigPathsPlugin(),
		],
		alias: {
			'~ops': path.resolve(__dirname, './src'),
			'~lib': path.resolve(__dirname, '../../lib/src'),
		},
	},
	output: {
		path: path.join(__dirname, 'dist'),
		publicPath: './',
		filename: '[name].[contenthash].js',
		clean: true,
	},
	module: {
		rules: [{
			test: /\.(j|t)sx?$/,
			exclude: /node_modules/,

			use: [{
				loader: 'thread-loader',
				options: {
					// There should be 1 cpu for the fork-ts-checker-webpack-plugin plugin (what a RAS)
					workers: os.cpus().length - 1,
				},
			}, {
				loader: 'ts-loader',
				options: {
					projectReferences: true,
					happyPackMode: true, // This implicitly sets "transpileOnly" to be true anyway
					transpileOnly: true,
				},
			}],

		}, {
			test: /\.s[ac]ss$/i,
			use: [
				'style-loader',
				'css-loader',
				'sass-loader',
			],
		}],
	},
	plugins: [
		new ForkTsCheckerWebpackPlugin({
			typescript: {
				diagnosticOptions: {
					semantic: true,
					syntactic: true,
				},
			},
		}),
		new NodePolyfillPlugin(),
		new HtmlWebpackPlugin({
			template: path.join(__dirname, 'index.html'),
			filename: 'index.html',
		}),
		new CopyPlugin([
			{ from: 'public' },
		]),
	],
	cache: {
		type: 'filesystem',
		cacheDirectory: path.resolve(__dirname, '.webpack-cache'),
	},
	devServer: {
		publicPath: '/',
		open: false,
		port: 3000,
	},
	devtool: 'eval-cheap-source-map',
};
```

Running this will throw the error I posted above. I've dug into this, and I think I can tell roughly what is going wrong, but I don't know enough about ts-loader architecture to be sure. The line it's failing on is in `src/serviceHost.ts`. Below is the transpiled line from my node_modules.

`const resolveSync = resolver_1.makeResolver(loader._compiler.options);`

`_compiler` doesn't exist on loader, I think this _may_ be because to use `ts-loader` you need to use the `use` syntax, rather than just defining the loader in the root of the rule. I've console.logged `loader` and this is what was returned:

```json
{
	"version": 2,
	"fs": { ...skipped },
	"options": {
		"context": "/Users/afr/Source/cuvva/monorepo/js/react/src/app/ops"
	},
	"webpack": true,
	"thread-loader": true,
	"sourceMap": false,
	"target": "web",
	"resourceQuery": "",
	"rootContext": "/Users/afr/Source/cuvva/monorepo/js/react/src/app/ops",
	"context": "/Users/afr/Source/cuvva/monorepo/js/react/src/app/ops/src",
	"loaderIndex": 0,
	"loaders": [
		{
			"path": "/Users/afr/Source/cuvva/monorepo/js/react/node_modules/ts-loader/index.js",
			"query": "??ruleSet[1].rules[0].use[1]",
			"fragment": "",
			"options": {
				"projectReferences": true,
				"happyPackMode": true,
				"transpileOnly": true
			},
			"ident": "ruleSet[1].rules[0].use[1]",
			"data": null,
			"pitchExecuted": true,
			"normalExecuted": true,
			"request": "/Users/afr/Source/cuvva/monorepo/js/react/node_modules/ts-loader/index.js??ruleSet[1].rules[0].use[1]"
		}
	],
	"resourcePath": "/Users/afr/Source/cuvva/monorepo/js/react/src/app/ops/src/index.tsx",
	"resourceFragment": "",
	"resource": "/Users/afr/Source/cuvva/monorepo/js/react/src/app/ops/src/index.tsx",
	"request": "/Users/afr/Source/cuvva/monorepo/js/react/node_modules/ts-loader/index.js??ruleSet[1].rules[0].use[1]!/Users/afr/Source/cuvva/monorepo/js/react/src/app/ops/src/index.tsx",
	"remainingRequest": "/Users/afr/Source/cuvva/monorepo/js/react/src/app/ops/src/index.tsx",
	"currentRequest": "/Users/afr/Source/cuvva/monorepo/js/react/node_modules/ts-loader/index.js??ruleSet[1].rules[0].use[1]!/Users/afr/Source/cuvva/monorepo/js/react/src/app/ops/src/index.tsx",
	"previousRequest": "",
	"query": {
		"projectReferences": true,
		"happyPackMode": true,
		"transpileOnly": true
	},
	"data": null
}
```

I think the main error is that for some reason `_compiler` is just not attached to the loader object. I edited the code locally to replace the line above to:

`const resolveSync = resolver_1.makeResolver(loader.query);`

This works, but it falls over further down the line with an error saying `loader._compiler.hooks` failed as `_compiler` is undefined. So looks like a larger issue than just the options.

### Location of a Minimal Repository that Demonstrates the Issue.

I can provide this if needed, although I think there is enough detail above.

**Comment by 0xdeafcafe** [comment]
It seems this was reported before (and fixed) in https://github.com/TypeStrong/ts-loader/issues/1206. However it seems to have broken again.

**Comment by marcelruiter** [comment]
any updates on this issue?

**Comment by 0xdeafcafe** [comment]
We ended up migrating to Vite
