### ISSUE TITLE
Tests fail on WIndows right from the off

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/ts-loader#136]
Hello!

I was trying to make a contribution and I discovered that right from the off 2 of the tests fail on Windows (ie before I've made any changes).  Any idea why this might be?  And why it doesn't show up in AppVeyor?

The only difference between my machine and AppVeyor that I can see is I'm using node v4.2.2 and npm v3.5.0.  I wouldn't have thought either was significant....

```
  63 passing (1m)
  2 failing

  1) issue81 should have the correct output:

      Uncaught AssertionError: bundle.js.map is different between actual and expected
      + expected - actual

      -{"version":3,"sources":["webpack:///webpack/bootstrap [hash]","webpack:///./a.ts"],"names":["bar","Foo"],"mapping
s":";AAAA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;AAEA;AACA;AACA,uBAAe;AACf;AACA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;;A
AGA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;;;;;;;;;;;ACtCA,KAAI,UAAU,GAAI,aAAQ,UAAK,UAAU,IAAK,UAAU,UAAU,EAAE,MAAM,EAAE,GA
AG,EAAE,IAAI,EAAE;AACnF,SAAI,CAAC,GAAG,SAAS,CAAC,MAAM;SAAE,CAAC,GAAG,CAAC,GAAG,CAAC,GAAG,MAAM,GAAG,IAAI,KAAK,IAAI,GAAG,I
AAI,GAAG,MAAM,CAAC,wBAAwB,CAAC,MAAM,EAAE,GAAG,CAAC,GAAG,IAAI;SAAE,CAAC,CAAC;AAC7H,SAAI,OAAO,OAAO,KAAK,QAAQ,IAAI,OAAO,OAA
O,CAAC,QAAQ,KAAK,UAAU,EAAE,CAAC,GAAG,OAAO,CAAC,QAAQ,CAAC,UAAU,EAAE,MAAM,EAAE,GAAG,EAAE,IAAI,CAAC,CAAC,KAC1H,KAAK,IAAI,CA
AC,GAAG,UAAU,CAAC,MAAM,GAAG,CAAC,EAAE,CAAC,IAAI,CAAC,EAAE,CAAC,EAAE,EAAE,IAAI,CAAC,GAAG,UAAU,CAAC,CAAC,CAAC,EAAE,CAAC,GA
AG,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,GAAG,CAAC,CAAC,MAAM,EAAE,GAAG,EAAE,CAAC,CAAC,GAAG,CA
AC,CAAC,MAAM,EAAE,GAAG,CAAC,KAAK,CAAC,CAAC;AAClJ,YAAO,CAAC,GAAG,CAAC,IAAI,CAAC,IAAI,MAAM,CAAC,cAAc,CAAC,MAAM,EAAE,GAAG,E
AAE,CAAC,CAAC,EAAE,CAAC,CAAC;EACjE,CAAC;AAJF,cAAa,MAAW;AACpBA,YAAOA,MAAMA,CAACA;EACjBA;AAED;;EAGCC;AAHD,mBAAC,GAAG,CAQH,
EAAE,GAAG,CAAC,C","file":"bundle.js","sourcesContent":[" \t// The module cache\n \tvar installedModules = {};\n\n \t// T
he require function\n \tfunction __webpack_require__(moduleId) {\n\n \t\t// Check if module is in cache\n \t\tif(install
edModules[moduleId])\n \t\t\treturn installedModules[moduleId].exports;\n\n \t\t// Create a new module (and put it into
the cache)\n \t\tvar module = installedModules[moduleId] = {\n \t\t\texports: {},\n \t\t\tid: moduleId,\n \t\t\tloaded:
false\n \t\t};\n\n \t\t// Execute the module function\n \t\tmodules[moduleId].call(module.exports, module, module.export
s, __webpack_require__);\n\n \t\t// Flag the module as loaded\n \t\tmodule.loaded = true;\n\n \t\t// Return the exports
of the module\n \t\treturn module.exports;\n \t}\n\n\n \t// expose the modules object (__webpack_modules__)\n \t__webpac
k_require__.m = modules;\n\n \t// expose the module cache\n \t__webpack_require__.c = installedModules;\n\n \t// __webpa
ck_public_path__\n \t__webpack_require__.p = \"\";\n\n \t// Load entry module and return exports\n \treturn __webpack_re
quire__(0);\n\n\n\n/** WEBPACK FOOTER **\n ** webpack/bootstrap [hash]\n **/","\r\nfunction bar(target: any) {\r\n    re
turn target;\r\n}\r\n\r\n@bar\r\nclass Foo {\r\n    \r\n}\n\n\n/** WEBPACK FOOTER **\n ** ./a.ts\n **/"],"sourceRoot":""
}
      +{"version":3,"sources":["webpack:///webpack/bootstrap [hash]","webpack:///./a.ts"],"names":["bar","Foo"],"mapping
s":";AAAA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;AAEA;AACA;AACA,uBAAe;AACf;AACA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;;A
AGA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;;;;;;;;;;;ACtCA,KAAI,UAAU,GAAI,aAAQ,UAAK,UAAU,IAAK,UAAU,UAAU,EAAE,MAAM,EAAE,GA
AG,EAAE,IAAI,EAAE;AACnF,SAAI,CAAC,GAAG,SAAS,CAAC,MAAM;SAAE,CAAC,GAAG,CAAC,GAAG,CAAC,GAAG,MAAM,GAAG,IAAI,KAAK,IAAI,GAAG,I
AAI,GAAG,MAAM,CAAC,wBAAwB,CAAC,MAAM,EAAE,GAAG,CAAC,GAAG,IAAI;SAAE,CAAC,CAAC;AAC7H,SAAI,OAAO,OAAO,KAAK,QAAQ,IAAI,OAAO,OAA
O,CAAC,QAAQ,KAAK,UAAU,EAAE,CAAC,GAAG,OAAO,CAAC,QAAQ,CAAC,UAAU,EAAE,MAAM,EAAE,GAAG,EAAE,IAAI,CAAC,CAAC,KAC1H,KAAK,IAAI,CA
AC,GAAG,UAAU,CAAC,MAAM,GAAG,CAAC,EAAE,CAAC,IAAI,CAAC,EAAE,CAAC,EAAE,EAAE,IAAI,CAAC,GAAG,UAAU,CAAC,CAAC,CAAC,EAAE,CAAC,GA
AG,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,GAAG,CAAC,CAAC,MAAM,EAAE,GAAG,EAAE,CAAC,CAAC,GAAG,CA
AC,CAAC,MAAM,EAAE,GAAG,CAAC,KAAK,CAAC,CAAC;AAClJ,YAAO,CAAC,GAAG,CAAC,IAAI,CAAC,IAAI,MAAM,CAAC,cAAc,CAAC,MAAM,EAAE,GAAG,E
AAE,CAAC,CAAC,EAAE,CAAC,CAAC;EACjE,CAAC;AAJF,cAAa,MAAW;AACpBA,YAAOA,MAAMA,CAACA;EACjBA;AAED;;EAGCC;AAHD,mBAAC,GAAG,CAQH,
EAAE,GAAG,CAAC,C","file":"bundle.js","sourcesContent":[" \t// The module cache\n \tvar installedModules = {};\n\n \t// T
he require function\n \tfunction __webpack_require__(moduleId) {\n\n \t\t// Check if module is in cache\n \t\tif(install
edModules[moduleId])\n \t\t\treturn installedModules[moduleId].exports;\n\n \t\t// Create a new module (and put it into
the cache)\n \t\tvar module = installedModules[moduleId] = {\n \t\t\texports: {},\n \t\t\tid: moduleId,\n \t\t\tloaded:
false\n \t\t};\n\n \t\t// Execute the module function\n \t\tmodules[moduleId].call(module.exports, module, module.export
s, __webpack_require__);\n\n \t\t// Flag the module as loaded\n \t\tmodule.loaded = true;\n\n \t\t// Return the exports
of the module\n \t\treturn module.exports;\n \t}\n\n\n \t// expose the modules object (__webpack_modules__)\n \t__webpac
k_require__.m = modules;\n\n \t// expose the module cache\n \t__webpack_require__.c = installedModules;\n\n \t// __webpa
ck_public_path__\n \t__webpack_require__.p = \"\";\n\n \t// Load entry module and return exports\n \treturn __webpack_re
quire__(0);\n\n\n\n/** WEBPACK FOOTER **\n ** webpack/bootstrap [hash]\n **/","\nfunction bar(target: any) {\n    return
 target;\n}\n\n@bar\nclass Foo {\n    \n}\n\n\n/** WEBPACK FOOTER **\n ** ./a.ts\n **/"],"sourceRoot":""}

      at C:\Source\ts-loader\test\run.js:238:28
      at Array.forEach (native)
      at Watching.handler (C:\Source\ts-loader\test\run.js:227:39)
      at Watching._done (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:81:7)
      at Watching.<anonymous> (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:61:18)
      at Compiler.emitRecords (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:282:37)
      at Watching.<anonymous> (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:58:19)
      at C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:275:11
      at Compiler.applyPluginsAsync (C:\Source\ts-loader\node_modules\tapable\lib\Tapable.js:60:69)
      at Compiler.afterEmit (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:272:8)
      at Compiler.<anonymous> (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:267:14)
      at C:\Source\ts-loader\node_modules\async\lib\async.js:52:16
      at done (C:\Source\ts-loader\node_modules\async\lib\async.js:246:17)
      at C:\Source\ts-loader\node_modules\async\lib\async.js:44:16
      at C:\Source\ts-loader\node_modules\graceful-fs\graceful-fs.js:42:10
      at C:\Source\ts-loader\node_modules\mocha\node_modules\graceful-fs\graceful-fs.js:104:5
      at FSReqWrap.oncomplete (fs.js:82:15)

  2) issue81 should work with transpile:

      Uncaught AssertionError: bundle.js.map is different between actual and expected
      + expected - actual

      -{"version":3,"sources":["webpack:///webpack/bootstrap [hash]","webpack:///./a.ts"],"names":["bar","Foo"],"mapping
s":";AAAA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;AAEA;AACA;AACA,uBAAe;AACf;AACA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;;A
AGA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;;;;;;;;;;;ACtCA,KAAI,UAAU,GAAI,aAAQ,UAAK,UAAU,IAAK,UAAU,UAAU,EAAE,MAAM,EAAE,GA
AG,EAAE,IAAI,EAAE;AACnF,SAAI,CAAC,GAAG,SAAS,CAAC,MAAM;SAAE,CAAC,GAAG,CAAC,GAAG,CAAC,GAAG,MAAM,GAAG,IAAI,KAAK,IAAI,GAAG,I
AAI,GAAG,MAAM,CAAC,wBAAwB,CAAC,MAAM,EAAE,GAAG,CAAC,GAAG,IAAI;SAAE,CAAC,CAAC;AAC7H,SAAI,OAAO,OAAO,KAAK,QAAQ,IAAI,OAAO,OAA
O,CAAC,QAAQ,KAAK,UAAU,EAAE,CAAC,GAAG,OAAO,CAAC,QAAQ,CAAC,UAAU,EAAE,MAAM,EAAE,GAAG,EAAE,IAAI,CAAC,CAAC,KAC1H,KAAK,IAAI,CA
AC,GAAG,UAAU,CAAC,MAAM,GAAG,CAAC,EAAE,CAAC,IAAI,CAAC,EAAE,CAAC,EAAE,EAAE,IAAI,CAAC,GAAG,UAAU,CAAC,CAAC,CAAC,EAAE,CAAC,GA
AG,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,GAAG,CAAC,CAAC,MAAM,EAAE,GAAG,EAAE,CAAC,CAAC,GAAG,CA
AC,CAAC,MAAM,EAAE,GAAG,CAAC,KAAK,CAAC,CAAC;AAClJ,YAAO,CAAC,GAAG,CAAC,IAAI,CAAC,IAAI,MAAM,CAAC,cAAc,CAAC,MAAM,EAAE,GAAG,E
AAE,CAAC,CAAC,EAAE,CAAC,CAAC;EACjE,CAAC;AAJF,cAAa,MAAW;AACpBA,YAAOA,MAAMA,CAACA;EACjBA;AAED;;EAGCC;AAHD,mBAAC,GAAG,CAQH,
EAAE,GAAG,CAAC,C","file":"bundle.js","sourcesContent":[" \t// The module cache\n \tvar installedModules = {};\n\n \t// T
he require function\n \tfunction __webpack_require__(moduleId) {\n\n \t\t// Check if module is in cache\n \t\tif(install
edModules[moduleId])\n \t\t\treturn installedModules[moduleId].exports;\n\n \t\t// Create a new module (and put it into
the cache)\n \t\tvar module = installedModules[moduleId] = {\n \t\t\texports: {},\n \t\t\tid: moduleId,\n \t\t\tloaded:
false\n \t\t};\n\n \t\t// Execute the module function\n \t\tmodules[moduleId].call(module.exports, module, module.export
s, __webpack_require__);\n\n \t\t// Flag the module as loaded\n \t\tmodule.loaded = true;\n\n \t\t// Return the exports
of the module\n \t\treturn module.exports;\n \t}\n\n\n \t// expose the modules object (__webpack_modules__)\n \t__webpac
k_require__.m = modules;\n\n \t// expose the module cache\n \t__webpack_require__.c = installedModules;\n\n \t// __webpa
ck_public_path__\n \t__webpack_require__.p = \"\";\n\n \t// Load entry module and return exports\n \treturn __webpack_re
quire__(0);\n\n\n\n/** WEBPACK FOOTER **\n ** webpack/bootstrap [hash]\n **/","\r\nfunction bar(target: any) {\r\n    re
turn target;\r\n}\r\n\r\n@bar\r\nclass Foo {\r\n    \r\n}\n\n\n/** WEBPACK FOOTER **\n ** ./a.ts\n **/"],"sourceRoot":""
}
      +{"version":3,"sources":["webpack:///webpack/bootstrap [hash]","webpack:///./a.ts"],"names":["bar","Foo"],"mapping
s":";AAAA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;AAEA;AACA;AACA,uBAAe;AACf;AACA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;;A
AGA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;;;;;;;;;;;ACtCA,KAAI,UAAU,GAAI,aAAQ,UAAK,UAAU,IAAK,UAAU,UAAU,EAAE,MAAM,EAAE,GA
AG,EAAE,IAAI,EAAE;AACnF,SAAI,CAAC,GAAG,SAAS,CAAC,MAAM;SAAE,CAAC,GAAG,CAAC,GAAG,CAAC,GAAG,MAAM,GAAG,IAAI,KAAK,IAAI,GAAG,I
AAI,GAAG,MAAM,CAAC,wBAAwB,CAAC,MAAM,EAAE,GAAG,CAAC,GAAG,IAAI;SAAE,CAAC,CAAC;AAC7H,SAAI,OAAO,OAAO,KAAK,QAAQ,IAAI,OAAO,OAA
O,CAAC,QAAQ,KAAK,UAAU,EAAE,CAAC,GAAG,OAAO,CAAC,QAAQ,CAAC,UAAU,EAAE,MAAM,EAAE,GAAG,EAAE,IAAI,CAAC,CAAC,KAC1H,KAAK,IAAI,CA
AC,GAAG,UAAU,CAAC,MAAM,GAAG,CAAC,EAAE,CAAC,IAAI,CAAC,EAAE,CAAC,EAAE,EAAE,IAAI,CAAC,GAAG,UAAU,CAAC,CAAC,CAAC,EAAE,CAAC,GA
AG,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,GAAG,CAAC,CAAC,MAAM,EAAE,GAAG,EAAE,CAAC,CAAC,GAAG,CA
AC,CAAC,MAAM,EAAE,GAAG,CAAC,KAAK,CAAC,CAAC;AAClJ,YAAO,CAAC,GAAG,CAAC,IAAI,CAAC,IAAI,MAAM,CAAC,cAAc,CAAC,MAAM,EAAE,GAAG,E
AAE,CAAC,CAAC,EAAE,CAAC,CAAC;EACjE,CAAC;AAJF,cAAa,MAAW;AACpBA,YAAOA,MAAMA,CAACA;EACjBA;AAED;;EAGCC;AAHD,mBAAC,GAAG,CAQH,
EAAE,GAAG,CAAC,C","file":"bundle.js","sourcesContent":[" \t// The module cache\n \tvar installedModules = {};\n\n \t// T
he require function\n \tfunction __webpack_require__(moduleId) {\n\n \t\t// Check if module is in cache\n \t\tif(install
edModules[moduleId])\n \t\t\treturn installedModules[moduleId].exports;\n\n \t\t// Create a new module (and put it into
the cache)\n \t\tvar module = installedModules[moduleId] = {\n \t\t\texports: {},\n \t\t\tid: moduleId,\n \t\t\tloaded:
false\n \t\t};\n\n \t\t// Execute the module function\n \t\tmodules[moduleId].call(module.exports, module, module.export
s, __webpack_require__);\n\n \t\t// Flag the module as loaded\n \t\tmodule.loaded = true;\n\n \t\t// Return the exports
of the module\n \t\treturn module.exports;\n \t}\n\n\n \t// expose the modules object (__webpack_modules__)\n \t__webpac
k_require__.m = modules;\n\n \t// expose the module cache\n \t__webpack_require__.c = installedModules;\n\n \t// __webpa
ck_public_path__\n \t__webpack_require__.p = \"\";\n\n \t// Load entry module and return exports\n \treturn __webpack_re
quire__(0);\n\n\n\n/** WEBPACK FOOTER **\n ** webpack/bootstrap [hash]\n **/","\nfunction bar(target: any) {\n    return
 target;\n}\n\n@bar\nclass Foo {\n    \n}\n\n\n/** WEBPACK FOOTER **\n ** ./a.ts\n **/"],"sourceRoot":""}

      at C:\Source\ts-loader\test\run.js:238:28
      at Array.forEach (native)
      at Watching.handler (C:\Source\ts-loader\test\run.js:227:39)
      at Watching._done (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:81:7)
      at Watching.<anonymous> (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:61:18)
      at Compiler.emitRecords (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:282:37)
      at Watching.<anonymous> (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:58:19)
      at C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:275:11
      at Compiler.applyPluginsAsync (C:\Source\ts-loader\node_modules\tapable\lib\Tapable.js:60:69)
      at Compiler.afterEmit (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:272:8)
      at Compiler.<anonymous> (C:\Source\ts-loader\node_modules\webpack\lib\Compiler.js:267:14)
      at C:\Source\ts-loader\node_modules\async\lib\async.js:52:16
      at done (C:\Source\ts-loader\node_modules\async\lib\async.js:246:17)
      at C:\Source\ts-loader\node_modules\async\lib\async.js:44:16
      at C:\Source\ts-loader\node_modules\graceful-fs\graceful-fs.js:42:10
      at C:\Source\ts-loader\node_modules\mocha\node_modules\graceful-fs\graceful-fs.js:104:5
      at FSReqWrap.oncomplete (fs.js:82:15)



```

**Comment by jbrantly** [comment]
It looks like the difference is in line endings, but [the test runner should be handling that](https://github.com/TypeStrong/ts-loader/blob/master/test/run.js#L229). Are you sure you have the latest master?

As a side note, I wanted to make sure you weren't addressing #111 since I've [got a branch open for that already](https://github.com/TypeStrong/ts-loader/tree/dont-force-module).

**Comment by johnnyreilly** [comment]
I was doing #111 actually - I thought it'd be an easy one to get my feet wet with. I'll leave it to you then.

Line endings you say? Is there a way to either make the test runner resilient to that? Alternatively, what gitconfig would get me the right stuff?

**Comment by johnnyreilly** [comment]
I see how you've tried to handle it. That should work!

**Comment by jbrantly** [comment]
That is so odd that on your machine the sourcemaps have \r\n but on mine (and apparently on AppVeyor) they don't. Also I didn't realize originally that those newlines were escaped (which is handled in your PR #138).

**Comment by johnnyreilly** [comment]
I know; I'm baffled as to why.  Maybe something in my git settings?

**Comment by johnnyreilly** [comment]
Nope. Nothing to report there.

**Comment by jbrantly** [comment]
@johnnyreilly I think I might have gotten this one figured out. I took a look at where exactly those newlines were coming from and they seemed to be coming directly from disk (not from babel, etc). On my Windows machine everything had LF. I checked my git settings and it seemed that I technically should have CRLF, but I didn't. I have no idea how that happened. In any case, I deleted the folder and recloned from github and sure enough my files on disk had CRLF and the test failed just like in your case. I spent some time trying to decide how to fix it but I've settled on updating the git attributes to just always checkout files with LF endings regardless of platform. After committing 2c197df I again deleted the folder and recloned from github and now all my files have LF endings and the tests pass.

Does this seem like a reasonable solution to you?

Alternatives would be:

1. Putting something in ts-loader itself to mess with newlines for the sourcemap's content (seems like not a good idea)
2. Adding something to the test runner to mess with newlines BEFORE hitting ts-loader. I did spend way too much time on this approach trying to get the existing `newLines` loader to run first but I was running into issues with sourcemaps that was becoming a mess to untangle. Another approach here would be to massage the files when copying them over to the staging directory.

I just felt like the git attributes approach was the simplest. I think Windows IDEs support both modes (I know VS Code does, for instance, which I use for ts-loader).

**Comment by johnnyreilly** [comment]
That totally sounds like the best solution. Thanks for looking into it! When I get to my keyboard I'll reclone and wait for the sweet experience of green tests. :smile:

**Comment by johnnyreilly** [comment]
PS I use atom for the most part

**Comment by johnnyreilly** [comment]
yup https://github.com/TypeStrong/ts-loader/commit/2c197dfbcb192fe471e5d0106ddfca3116de7656 resolves this
