### ISSUE TITLE
HappyPack no longer working with webpack@5 and ts-loader@9

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/ts-loader#1382]
### Expected Behaviour

No error when using `ts-loader@9` with `webpack@5` and `happypack` .

### Actual Behaviour

```sh-session
$ webpack
Happy[ts]: Version: 5.0.1. Threads: 2
Happy[ts]: All set; signaling webpack to proceed.
assets by status 1.85 KiB [cached] 1 asset
./src/index.ts 39 bytes [built] [code generated] [1 error]

ERROR in ./src/index.ts
Module build failed (from ./node_modules/happypack/loader.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/ts-loader/dist/index.js:14:21)
    at applySyncOrAsync (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/applyLoaders.js:350:21)
    at apply (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/applyLoaders.js:277:5)
    at /Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/applyLoaders.js:135:7
    at applyPitchLoader (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/applyLoaders.js:188:14)
    at applyPitchLoader (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/applyLoaders.js:196:14)
    at applyPitchLoaders (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/applyLoaders.js:226:4)
    at applyLoaders (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/applyLoaders.js:120:3)
    at HappyWorker.compile (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/HappyWorker.js:27:3)
    at COMPILE (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/HappyWorkerChannel.js:46:10)
    at process.accept (/Users/oliverash/Development/webpack-5-ts-loader-happypack/node_modules/happypack/lib/HappyWorkerChannel.js:75:7)
    at process.emit (node:events:394:28)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

webpack 5.58.1 compiled with 1 error in 416 ms
```

### Steps to Reproduce the Problem

Full reduced test case: https://github.com/OliverJAsh/webpack-5-ts-loader-happypack

I suspect `happypack` does not support webpack 5 yet. It hasn't been updated in a long time.

I don't think there's anything we can do from `ts-loader`'s side, but it might be worth updating the docs so we don't recommend `happypack` in the meantime?

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/OliverJAsh/webpack-5-ts-loader-happypack

**Comment by AlexeyRyazanov** [comment]
The same error with the same tool set: ts-loader@9.2.6 with webpack@5.67.0 and happypack@5.0.1

**Comment by eduardo-pinheiro** [comment]
I have the same issue, did someone manage to solve this?

**Comment by KatSick** [comment]
@eduardo-pinheiro I upgraded threads-loader to 4.0.2 and it works
