### ISSUE TITLE
`Cannot find module '/home/user/#dev/xxx/node_modules/ts-loader/index.js'` if the working directory path contains `#`

### ISSUE THREAD

**Issue by mirumirumi** [TypeStrong/ts-loader#1390]
I've been using the name "#dev" as the top directory name for development. Although I imagined some risks, I never faced any problems.

```
home/
└── Username/
    └── #dev/
        ├── repo
        ├── repo
        ├── ・
        ├── ・
        ├── ・
        └── and more...
```

However, when I tried to compile TypeScript using webpack and ts-loader for the first time, I discovered that `#` was probably the problem.

#### 1. install

```
npm install --save-dev ts-loader webpack webpack-cli
```
(I reproduced it even with this minimal pattern without TypeScript.)

versions:
```
ts-loader@9.2.6
webpack-cli@4.9.1
webpack@5.64.4
```

`npm list -g` : 

```
npm@8.1.0
```

#### 2. prepare config files

`tsconfig.json`  (I don't have TypeScript installed, so this may not be relevant, but just in case) : 

```json
{
    "compilerOptions": {
        "target": "es2015",
        "module": "es2015", 
        "strict": true,
        "esModuleInterop": true
    }
}
```

`webpack.config.js` : 

```js
const path = require("path");

module.exports = {
  mode: "development",
  entry: "./index.ts",
  output: {
    filename: "index.js",
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: "ts-loader",
      },
    ],
  },
  resolve: {
    extensions: [".ts", ".js"],
  },
};
```

index.ts: 

```ts
console.log("Hello!");
```

#### 3. build

```
npx webpack
```

### I got the following error

Console: 

```
ERROR in ../../#dev/repo-name/index.ts
Module build failed (from ../../#dev/repo-name/node_modules/ts-loader/index.js):
Error: Cannot find module '/home/Username/#dev/repo-name/node_modules/ts-loader/index.js'
Require stack:
- /home/Username/#dev/repo-name/node_modules/loader-runner/lib/loadLoader.js
- /home/Username/#dev/repo-name/node_modules/loader-runner/lib/LoaderRunner.js
- /home/Username/#dev/repo-name/node_modules/webpack/lib/NormalModule.js
- /home/Username/#dev/repo-name/node_modules/webpack/lib/NormalModuleFactory.js
- /home/Username/#dev/repo-name/node_modules/webpack/lib/Compiler.js
- /home/Username/#dev/repo-name/node_modules/webpack/lib/webpack.js
- /home/Username/#dev/repo-name/node_modules/webpack/lib/index.js
- /home/Username/#dev/repo-name/node_modules/webpack-cli/lib/webpack-cli.js
- /home/Username/#dev/repo-name/node_modules/webpack-cli/lib/bootstrap.js
- /home/Username/#dev/repo-name/node_modules/webpack-cli/bin/cli.js
- /home/Username/#dev/repo-name/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/home/Username/#dev/repo-name/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadLoader (/home/Username/#dev/repo-name/node_modules/loader-runner/lib/loadLoader.js:19:17)
    at iteratePitchingLoaders (/home/Username/#dev/repo-name/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/home/Username/#dev/repo-name/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule.doBuild (/home/Username/#dev/repo-name/node_modules/webpack/lib/NormalModule.js:743:3)
    at NormalModule.build (/home/Username/#dev/repo-name/node_modules/webpack/lib/NormalModule.js:892:15)
    at /home/Username/#dev/repo-name/node_modules/webpack/lib/Compilation.js:1311:12
```

(line:3, you can see the log "index.js not found in ts-loader". In fact, you can access the file with the exact same path.)

```
> cat /home/Username/#dev/repo-name/node_modules/ts-loader/index.js

var loader = require('./dist');

module.exports = loader;
```

### remove `#`

Under the exact same conditions, just remove the `#` from the file path and all problems will be solved and webpack will build successfully.

```
asset index.js 1.24 KiB [emitted] (name: main)
./index.ts 37 bytes [built] [code generated]
webpack 5.64.4 compiled successfully in 705 ms
```

### Finally

I'm really sorry if this is a known issue, if I've misreported it, or if you think this is a silly discussion.

**Comment by appzuka** [comment]
This is a known issue with webpack. See https://github.com/TypeStrong/ts-loader/issues/1366#issuecomment-971995352

**Comment by mirumirumi** [comment]
I did not check the webpack issue. Sorry about that.
So should I close this issue?

**Comment by mirumirumi** [comment]
ok, thanks.
