### ISSUE TITLE
API break notification: crash in resolveTypeReferenceDirective

### ISSUE THREAD

**Issue by RyanCavanaugh** [TypeStrong/ts-loader#1421]
Reusing some bits here

### Search Terms

path indexOf charCodeAt resolveTypeReferenceDirective typescript 4.7

### Expected Behavior

No crash

### Actual Behavior

```
/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:7690
        var index = path.indexOf("\\");
                         ^
TypeError: path.indexOf is not a function
    at normalizeSlashes (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:7690:26)
    at Object.combinePaths (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:7756:28)
    at /home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:41927:40
    at Object.firstDefined (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:407:26)
    at primaryLookup (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:41926:27)
    at Object.resolveTypeReferenceDirective (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:41885:24)
    at /home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/ts-node/src/resolver-functions.ts:135:14
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/ts-node/src/resolver-functions.ts:133:33)
    at actualResolveTypeReferenceDirectiveNamesWorker 
```

### Steps to reproduce the problem

See https://github.com/microsoft/TypeScript/issues/48020

See also https://github.com/TypeStrong/ts-node/issues/1647

**Comment by johnnyreilly** [comment]
Thanks for the heads up - I wasn't aware of this issue. 

I'm traveling at the moment and so only on my phone. 

It looks like the issue has been addressed in ts-node already. Probably taking the following PR as a basis, we could implement something similar in ts-loader.

https://github.com/TypeStrong/ts-node/pull/1648/files

**Comment by johnnyreilly** [comment]
I've dug a little further and it looks pretty likely that @cspotcode's work on ts-node will be reusable to solve this issue as well.  Sidebar, it's interesting to note how both projects have some kind of `TSCommon` concept in play to handle differing versions of TypeScript APIs: https://github.com/TypeStrong/ts-node/pull/1648/files#diff-5bee04288d96530d8348a983e503ec21efdea399fb8b1a3aedb4bd51b03a6f5dR12

**Comment by johnnyreilly** [comment]
Closing as fixed - not sure what @stalebot is on about
