### ISSUE TITLE
 TypeError: loaderContext.getOptions is not a function

### ISSUE THREAD

**Issue by albizeka** [TypeStrong/ts-loader#1484]
yntax Error: TypeError: loaderContext.getOptions is not a function

 @ multi (webpack)-dev-server/client?http://localhost:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

I upgraded my app from vue 3 js to vue 3 typescript and this error occurs:

I tried to downgrade webpack to version 4, also the ts-loader to 8.2.0 and node version but non of these works.

Does anybody solved this issue?

**Comment by stefankuburovic** [comment]
I have same issue, after upgrading it to latest version

**Comment by IceApriler** [comment]
Me too. I used vue-cli to initialize a vue3 project and then executed `vue add electron-builder`.
Run `npm run serve` was successfully.
Run `npm run electron:serve` was faild.
```bash
 error  in ./src/background.ts

Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/Users/qimengjie/Myfile/www/ybj/vue3-ts-sass-quick-start/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/Users/qimengjie/Myfile/www/ybj/vue3-ts-sass-quick-start/node_modules/ts-loader/dist/index.js:14:21)

 @ multi ./src/background.ts
```

**Comment by luntdotp** [comment]
I am also experiencing this issue on a vue 3 ts project

**Comment by alexander-akait** [comment]
You need webpack v5 to use the latest version of `ts-loader`
