### ISSUE TITLE
Error: Debug Failure. False expression after upgrading to Typescript 5.0.2

### ISSUE THREAD

**Issue by christiango** [TypeStrong/ts-loader#1604]
### Expected Behaviour
Loads without any errors as it did in typescript 4.9.2

### Actual Behaviour
We get an error along the lines

Module build failed (from ../../packages/build-tools/node_modules/ts-loader/index.js):
Error: Debug Failure. False expression.
    at onBeforeVisitNode (D:\repo\node_modules\typescript\lib\typescript.js:88240:19)
    at saveStateAndInvoke (D:\repo\node_modules\typescript\lib\typescript.js:88214:7)
    at sourceElementVisitor (D:\repo\node_modules\typescript\lib\typescript.js:88255:14)
    at visitArrayWorker (D:\repo\node_modules\typescript\lib\typescript.js:85415:51)
    at visitNodes2 (D:\repo\node_modules\typescript\lib\typescript.js:85386:21)
    at visitLexicalEnvironment (D:\repo\node_modules\typescript\lib\typescript.js:85442:18)
    at visitSourceFile (D:\repo\node_modules\typescript\lib\typescript.js:88476:9)
    at saveStateAndInvoke (D:\repo\node_modules\typescript\lib\typescript.js:88215:23)
    at transformSourceFile (D:\repo\node_modules\typescript\lib\typescript.js:88205:23)
    at transformSourceFileOrBundle (D:\repo\node_modules\typescript\lib\typescript.js:88190:14)

### Steps to Reproduce the Problem
Upgrade a project using  "ts-loader": "^9.4.2" to "typescript": "~5.0.2" and start your webpack dev server

### Location of a Minimal Repository that Demonstrates the Issue.
Still todo, just reporting for now since I suspect others are hitting this

**Comment by christiango** [comment]
It may be related to our usage of react-refresh:

    options: {
          getCustomTransformers: () => ({
            before: [ReactRefreshTypeScript()]
          })
        }

**Comment by MirKml** [comment]
I upgraded all tooling for TS 5+, latest webpack, ts-loader and all works fine. So most likely it's caused by your custom react-refresh usaged

**Comment by christiango** [comment]
Agreed, sorry I thought I closed this last week!
