### ISSUE TITLE
Errors when using "all-in-one" JS + typings packages in hybrid JS/TS projects

### ISSUE THREAD

**Issue by mischkl** [TypeStrong/ts-loader#347]
Using:
**ts-loader@0.9.5**
**typescript@2.0.6**
**webpack@2.1.0-beta.25** (but also some problems with v1.8.x)

We have a project that is being migrated from ES5 to TS, so it consists of a mix of both kinds of files. .JS files are handled as CommonJS and bundled directly by Webpack, while ts-loader is configured to only handle .ts files. This is a setup that we have been using without issue for the last half year or so, which has so far enabled a smooth migration path with interoperability between JS and TS code. We even managed to upgrade to Webpack 2.x and TypeScript 2.x without any serious issues.

When we recently attempted to add RxJS 5.0.0-rc.1 to our project, however, it caused the TypeScript compiler to output a number of errors and ultimately fail to build. For simple imports from rxjs, TypeScript complains about not finding various names within the rxjs type definition files. This problem affects both Webpack 1.x and 2.x .

In addition, when using Webpack 2.x, TypeScript crashes as soon as one attempts to use rxjs classes with basic operators such as `Observable.scan,`, with the following message 

```
TypeError: Cannot read property 'id' of undefined
    at getNodeId (C:\workspace\myproject\node_modules\typescript\lib\typescript.js:16509:18)
    at getNodeLinks (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:16992:26)
    at checkExpressionCached (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:28851:25)
    at c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19466:25
    at Object.map (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:1240:29)
    at getTypeOfVariableOrParameterOrProperty (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19464:44)
    at getTypeOfSymbol (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19607:24)
    at getTypeOfAlias (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19590:23)
    at getTypeOfSymbol (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19619:24)
    at checkIdentifier (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:24671:24)
    at checkExpressionWorker (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:28932:28)
    at checkExpression (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:28912:42)
    at getBaseConstructorTypeOfClass (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19726:43)
    at resolveAnonymousTypeMembers (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:20406:47)
    at resolveStructuredTypeMembers (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:20432:21)
    at getSignaturesOfStructuredType (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:20623:32)
    at getSignaturesOfType (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:20633:20)
```

Interestingly, if all *.d.ts files are deleted from the `rxjs` package and moved into `node_modules/@types/rxjs`, and the `Rx.d.ts` file there renamed to `index.d.ts`, then everything compiles and works just as expected.

I originally reported this issue here: https://github.com/ReactiveX/rxjs/issues/2058. Since then I've verified that the problem lies with `ts-loader`, since `awesome-typescript-loader` works without issue. A demo project that illustrates the issue can be found here: https://github.com/mischkl/demo-rxjs-typescript-webpack-error

**Comment by johnnyreilly** [comment]
Thanks for the repro - haven't looked at WebPack 2.0 and so not sure if ts-loader will work with it. Could be worth checking other WebPack 2.0 issues listed against ts-loader. Some people are using it with ts-loader but we do not directly support it /use it as it's still beta.

**Comment by Aleksion** [comment]
I can confirm that my project also worked when switching out ts-loader for awesome-typescript-loader - as referenced in #349 

The query options for babel didn't have anything to do with it, since the babelrc file was providing what was necessary. And even without babel and just typescript it was throwing errors.

**Comment by davidspiess** [comment]
Same problem here with webpack 1 after adding moment-range typings with npm:

**ts-loader@1.0.0
typescript@2.0.6
webpack@1.13.3**

```
ERROR in ./src/index.js
Module build failed: TypeError: Cannot read property 'id' of undefined
    at getNodeId (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:17133:18)
    at getNodeLinks (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:17617:26)
    at checkExpressionCached (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:29532:25)
    at C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:20106:25
    at Object.map (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:1249:29)
    at getTypeOfVariableOrParameterOrProperty (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:20104:44)
    at getTypeOfSymbol (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:20253:24)
    at getTypeOfAlias (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:20236:23)
    at getTypeOfSymbol (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:20265:24)
    at checkIdentifier (C:\Users\DMair\Code\widget-client\node_modules\typescript\lib\typescript.js:25334:24)
 @ multi main
```

```json
{
    "compilerOptions": {
        "target": "es5",
        "jsx": "react",
        "noImplicitAny": false,
        "allowJs": true,
        "sourceMap": true
    },
    "exclude": [
        "node_modules"
    ]
}
```
