### ISSUE TITLE
Error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by darewreck54** [TypeStrong/ts-loader#467]
I just clone the project, and ran "npm install" on the examples/webpack2-gulp-react-flux-babel-karma.  

After running "npm run build," I get the following error:

`ERROR in ./src/main.tsx
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/"
    at /ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-core/lib/transformation/file/options/option-manager.js:292:19
    at Array.map (native)
    at OptionManager.resolvePresets (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-core/lib/transformation/file/options/option-manager.js:274:20)
    at OptionManager.mergePresets (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-core/lib/transformation/file/options/option-manager.js:263:10)
    at OptionManager.mergeOptions (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-core/lib/transformation/file/options/option-manager.js:248:14)
    at OptionManager.init (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
    at File.initOptions (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/ts-loader/examples/webpack2-gulp-react-flux-babel-karma/node_modules/babel-loader/lib/index.js:133:12)
`

I"m not really sure what the issue is.  I figured it should work right out of the box, but that doesn't seem the case.

Any help appreciated,
Thanks,
Derek

**Comment by darewreck54** [comment]
it seems that you have to create a .babelrc file with the options in there.  Anyone know why that is?  

.babelrc

`{
  "presets": [
    [
      "es2015", {
        "modules": false
      }
    ],
    "es2016",
    "react"
  ]
}`

**Comment by johnnyreilly** [comment]
The Babel options are specified in the webpack.config.js: https://github.com/TypeStrong/ts-loader/blob/master/examples/webpack2-gulp-react-flux-babel-karma/webpack.config.js

The preset shouldn't be required.

**Comment by johnnyreilly** [comment]
Looks good to me; I just did the following:

```
git clone https://github.com/TypeStrong/ts-loader.git
cd ./ts-loader/examples/webpack2-gulp-react-flux-babel-karma/
npm install
npm run serve
```

All good
