### ISSUE TITLE
watcher.mtimes undefined makes hot reload crash

### ISSUE THREAD

**Issue by mgiraud** [TypeStrong/ts-loader#479]
Hello,

I was trying to setup a vue-ts-webpack2 stack. I have no problem with the builds, but the following error occurs when hot-reloading the build.
I use the following command : `webpack-dev-server --inline --hot`

### The tracelog
```
watch-run.js:15
        Object.keys(watcher.mtimes)
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Compiler.<anonymous> (node_modules/ts-loader/dist/watch-run.js:15:16)
    at next (node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.compilerInvalid (node_modules/webpack-dev-middleware/lib/Shared.js:144:5)
    at next (node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.compiler.plugin (node_modules/webpack/lib/CachePlugin.js:32:5)
    at Compiler.applyPluginsAsyncSeries (node_modules/tapable/lib/Tapable.js:142:13)
    at Watching._go (node_modules/webpack/lib/Compiler.js:43:16)
    at Watching.invalidate (node_modules/webpack/lib/Compiler.js:121:8)
    at Watching.<anonymous> (node_modules/webpack/lib/Compiler.js:106:8)
```

### The composer

```
{
  "name": "vuejs-app",
  "version": "1.0.0",
  "repository": {},
  "license": "MIT",
  "scripts": {
    "dev": "webpack-dev-server --inline --hot --config Resources/webpack/build/webpack.config.js "
  },
  "dependencies": {
    "css-loader": "^0.26.1",
    "less": "^2.7.2",
    "less-loader": "^2.2.3",
    "ts-loader": "^2.0.0",
    "typescript": "^2.1.6",
    "vue": "^2.1.10",
    "vue-loader": "^11.1.0",
    "vue-template-compiler": "^2.1.10",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.2.1"
  }
}
```

### The webpack config
```
const config = {
    entry: { app: './Resources/webpack/js/app.ts', },
    output: { filename: 'app.js' },
    // resolve TypeScript and Vue file
    resolve: {
        extensions: ['*', '.ts', '.vue', '.js']
    },
    module: {
        rules: [
            { test: /\.vue$/, loader: 'vue-loader' },
            { test: /\.ts$/, loader: 'ts-loader', options: { appendTsSuffixTo: [/\.vue$/] } },
        ]
    },
    plugins: []
};
```

**Comment by bancek** [comment]
As a temporary fix you can add `"watchpack": "1.2.1"` to your dependencies. It seems that `watchpack` changed the internal api for watching files.

**Comment by Tronix117** [comment]
I have exactly the same issue and CI builds are broken

**Comment by bancek** [comment]
This has been caused by https://github.com/webpack/watchpack/commit/415086cb172d2dc85b85d4bfc54767232fee60a6

**Comment by DDtMM** [comment]
I have a similar issue with Angular2.  Adding the dependency `"watchpack": "1.2.1"` works as suggested.

**Comment by johnnyreilly** [comment]
Okay this was a breaking change in webpack. ts-loader depends on an undocumented part of the API. That is being added back to webpack until we  can better work around this.
