### ISSUE TITLE
You may need an appropriate loader to handle this file type. SyntaxError: Unexpected token (32:25)

### ISSUE THREAD

**Issue by jrmcdona** [TypeStrong/ts-loader#490]
Hi, I am using ts-loader.
{ test: /\.ts$/, loader: 'ts-loader', query: { silent: true } },

However, I am still getting these error trying to run a karma test.  Details are below!   Any ideas would be great as I keep trying various things.

```
ERROR in ./ClientApp/app/main.spec.ts
Module parse failed: C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\**ClientApp\app\main.spec.ts Unexpected token (32:25)
You may need an appropriate loader to handle this file type.**
SyntaxError: Unexpected token (32:25)
    at Parser.pp$4.raise (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.expect (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:597:28)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:1852:40)
    at Parser.pp$3.parseExprAtom (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$1.parseVar (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:1034:28)
    at Parser.pp$1.parseVarStatement (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:917:10)
    at Parser.pp$1.parseStatement (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:706:19)
    at Parser.pp$1.parseTopLevel (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\v-jormc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\acorn\dist\acorn.js:3098:39)
webpack: Failed to compile.
```

My test file looks like this:

```
import 'core-js'; // ES6 + reflect-metadata
// zone.js
import 'zone.js/dist/zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/async-test';
import 'zone.js/dist/jasmine-patch';

// TestBed initialization
import { TestBed } from '@angular/core/testing';
import {
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';

TestBed.initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting()
);


// load all specs in ./src .
const context = (require as any).context('./', true, /\.spec\.ts$/);
context.keys().map(context);
```

**Comment by jrmcdona** [comment]
If I change my test file to not include all those imports and do something basic.   Like this below.  It successfully runs.    

describe('sub test', () => {
    it('always fails', () => {
        expect(0).toBe(1);
    });
});

**Comment by johnnyreilly** [comment]
It might be worth looking at the setup in some of our examples that use karma: https://github.com/TypeStrong/ts-loader/tree/master/examples/webpack2-gulp-react-flux-babel-karma

FWIW I believe they use a js file to load all the typescript tests: https://github.com/TypeStrong/ts-loader/blob/master/examples/webpack2-gulp-react-flux-babel-karma/test/main.js

Can't quite remember why but there was a reason

https://github.com/TypeStrong/ts-loader/blob/master/examples/webpack2-gulp-react-flux-babel-karma/karma.conf.js

**Comment by jrmcdona** [comment]
Ok thanks, checking that out.  I am still on webpack1 so I think I best go ahead and migrate to have apples to apples.
