### ISSUE TITLE
ts-loader does not work with hybrid ts and js using (allowJs: true)

### ISSUE THREAD

**Issue by nojvek** [TypeStrong/ts-loader#641]
I've created a vanilla-js example: 

See: https://github.com/nojvek/ts-loader/commit/bc4664f9e3f632c75d0ae43ae92ef39e2e9080d4

```
module.exports = {
    devtool: 'inline-source-map',
    entry: './src/index.js',
    output: { filename: 'dist/index.js' },
    module: {
        rules: [
            {
                test: /\.(ts|js)?$/,
                loader: 'ts-loader'
            }
        ]
    },
    resolve: {
        extensions: [ '.ts', '.js' ]
    }
};
```

```
ERROR in ./src/index.js
Module build failed: Error: Could not find file: '/Users/nojvek/git/ts-loader/examples/vanilla-js/src/index.js'.
    at getValidSourceFile (/Users/nojvek/git/ts-loader/examples/vanilla-js/node_modules/typescript/lib/typescript.js:91281:23)
    at Object.getEmitOutput (/Users/nojvek/git/ts-loader/examples/vanilla-js/node_modules/typescript/lib/typescript.js:91661:30)
    at getEmit (/Users/nojvek/git/ts-loader/examples/vanilla-js/node_modules/ts-loader/dist/index.js:152:43)
    at successLoader (/Users/nojvek/git/ts-loader/examples/vanilla-js/node_modules/ts-loader/dist/index.js:42:11)
    at Object.loader (/Users/nojvek/git/ts-loader/examples/vanilla-js/node_modules/ts-loader/dist/index.js:29:12)
```

Typescript is able to compile the js files just fine after adding "outDir" option. ts-loader seems to error out.

End goal: switch out babel-loader and use ts-loader for our js project. Slowly add `//@ts-check` to files that we want to be typechecked

**Comment by johnnyreilly** [comment]
Have you tried adding the `entryFileIsJs` option?

**Comment by nojvek** [comment]
Thanks. That worked. Also sent you example PR with js ts hybrid.
