### ISSUE TITLE
exnext modules + allowJS + require results in error

### ISSUE THREAD

**Issue by bsouthga** [TypeStrong/ts-loader#651]
It appears that `require`-ing a javascript file instead of `import`-ing it with `esnext` modules + `allowJs` results in the following bug: 

```
ts-loader: Using typescript@2.5.3 and /Users/bensouthgate/projects/ts-loader-js-import/tsconfig.json
Hash: 0cb013a474fc1faf04f4
Version: webpack 3.7.1
Time: 702ms
    Asset     Size  Chunks             Chunk Names
bundle.js  8.15 kB       0  [emitted]  main
   [0] ./index.ts 198 bytes {0} [built]
   [1] ./ts-import.ts 74 bytes {0} [built]
   [2] ./import.js 733 bytes {0} [built] [failed] [1 error]

ERROR in ./import.js
Module build failed: Error: Could not find file: '/Users/bensouthgate/projects/ts-loader-js-import/import.js'.
    at getValidSourceFile (/Users/bensouthgate/projects/ts-loader-js-import/node_modules/typescript/lib/typescript.js:91389:23)
    at Object.getEmitOutput (/Users/bensouthgate/projects/ts-loader-js-import/node_modules/typescript/lib/typescript.js:91769:30)
    at getEmit (/Users/bensouthgate/projects/ts-loader-js-import/node_modules/ts-loader/dist/index.js:152:43)
    at successLoader (/Users/bensouthgate/projects/ts-loader-js-import/node_modules/ts-loader/dist/index.js:42:11)
    at Object.loader (/Users/bensouthgate/projects/ts-loader-js-import/node_modules/ts-loader/dist/index.js:29:12)
 @ ./index.ts 4:15-34
npm ERR! Test failed.  See above for more details.
```

Long story short, the following produces the above error: 

```
// this results in error
const { default: jsImport } = require('./import');
```

while this does not (using the same config)

```
// this does not
import jsImport from './import';
```

### Full code for bug

- Url to repo showing bug: https://github.com/bsouthga/ts-loader-require-bug

### Webpack config

```javascript

module.exports = {
  devtool: 'inline-source-map',
  entry: './index.ts',
  output: {
    filename: 'bundle.js'
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js']
  },
  module: {
    loaders: [
      {
        test: /\.(j|t)s$/,
        use: [
          {
            loader: 'ts-loader'
          }
        ]
      }
    ]
  }
}
```

### `tsconfig.json`

```javascript
{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "allowJs": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "allowSyntheticDefaultImports": true,
    "outDir": "dist",
    "lib": ["es6", "dom"],
    "jsx": "react",
    "baseUrl": "./",
    "paths": {
      "@lib/*": ["./deep/src/lib/*"]
    }
  },
  "include": [
    "./**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

### `index.ts` (entry)

```typescript
import { log } from './ts-import';

declare var require: (mod: string) => any;

// this results in error
const { default: jsImport } = require('./import');

// // this does not
// import jsImport from './import';

log();
jsImport.test();
```

### `import.js` (js import file)

```javascript
export default {
  test() {
    console.log(`js-import`);
  }
}
```

**Comment by johnnyreilly** [comment]
That's interesting behaviour... Thanks for a thorough repro. I'm fairly busy with v3.0 right now and so I can't promise to look at this soon. That said, I'm always happy to provide support if you wanted to look into it (and I always appreciate help!)

**Comment by bsouthga** [comment]
yeah happy to take a look, my guess is something is snafued around what determines a valid source file within typescript upon calling `getValidSourceFile` -- its possible this is a but in typescript itself.

**Comment by johnnyreilly** [comment]
Could be worth checking if this issue persists with ts-loader v3.  There were relevant changes around `allowJs` support as part of that.

**Comment by bsouthga** [comment]
👏  looks like it works with version 3, thanks!

**Comment by johnnyreilly** [comment]
Great news!
