### ISSUE TITLE
ts-loader 4.0.1 throw error while packing with backpack, a webpack variant

### ISSUE THREAD

**Issue by Mark083** [TypeStrong/ts-loader#744]
### Instead I receive the following error :
```
> myTestProject@0.0.1 build /home/myUser/myProjectFolder/myTestProject  
> backpack build

 ERROR  Failed to compile with 1 errors00:34:00

 error  in ./src/main.ts

Module build failed: TypeError: Cannot read property 'afterCompile' of undefined
    at successfulTypeScriptInstance (/home/myUser/myProjectFolder/myTestProject/node_modules/ts-loader/dist/instances.js:147:28)
    at Object.getTypeScriptInstance (/home/myUser/myProjectFolder/myTestProject/node_modules/ts-loader/dist/instances.js:48:12)
    at Object.loader (/home/myUser/myProjectFolder/myTestProject/node_modules/ts-loader/dist/index.js:16:41)

 @ multi ./src/main.ts


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myTestProject@0.0.1 build: `backpack build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myTestProject@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myUser/.npm/_logs/2018-01-01T01_01_01_010Z-debug.log
```

### Steps to Reproduce the Problem
```
mkdir -p myProjectName/{prd,src/M}
cd myProjectName
npm init -y
npm install -D jshint ts-loader typescript backpack-core copy-webpack-plugin
// above to work need to be ts-loader@3.5.0
npm install -S asciify
cat <<EOT> ./package.json
{
  "name": "myProjectName",
  "version": "0.0.1",
  "description": "learn",
  "private": true,
  "scripts": {
    "start": "node ./prd/main.js",
    "dev": "backpack dev",
    "build": "backpack build"
  },
  "license": "MIT",
  "devDependencies": {
    "backpack-core": "^0.5.0",
    "copy-webpack-plugin": "^4.5.0",
    "jshint": "^2.9.5",
    "ts-loader": "^4.0.1",
    "typescript": "^2.7.2"
  },
  "dependencies": {
    "@types/asciify": "^1.3.29",
    "asciify": "^1.3.5"
  }
}
EOT
cat <<EOT> tsconfig.json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "strict": true,
    "sourceMap": true,
    "allowSyntheticDefaultImports": true
  }
}
EOT
cat <<EOT> backpack.config.js
var path = require("path");
var CopyWebpackPlugin = require('copy-webpack-plugin')
module.exports = {
  webpack: (config, options, webpack) => {
    config.entry.main = ["./src/main.ts"];
    config.output.path = path.resolve("./prd");
    config.target = "node";
    config.node.__filename = true;
    config.node.__dirname = true;
    config.resolve = {
      extensions: [".ts", ".js", ".json"]
    };
    config.module.rules = [];
    config.module.rules.push({ test: /\.ts$/, loader: "ts-loader" });
    config.plugins.push(
	new CopyWebpackPlugin([
		{ from: 'node_modules/asciify/lib/figlet-js/fonts/short.flf', to: 'node_modules/asciify/lib/figlet-js/fonts/short.flf' }
	])
    );
    return config;
  }
};
EOT
cat <<EOT> ./src/M/AuxClass.ts
class AuxClass{
	getMessage(){
		return "Class Works!";
	}
}
export { AuxClass }
EOT
cat <<EOT> ./src/main.ts
import { AuxClass } from "./M/AuxClass"
export class main {
  init() {
    let a = new AuxClass();
    let text = a.getMessage();
    let fontName = "short";
    let callback = function(err: any, value: any): void {
      if (err != null) {
        console.log(err);
      }
      console.log(value);
    };
    var asciify = require("./../node_modules/asciify/index.js");
    asciify(text, fontName, callback);
  }
}
let m = new main();
m.init();
EOT
```

### StackOverflow Question  
https://stackoverflow.com/q/49271246/9217154

**Comment by johnnyreilly** [comment]
I suspect backpack isn't webpack 4 compliant. Closing as nothing to do I think.
