### ISSUE TITLE
Module Build Failed : Cannot read property 'fileTimestamps' of undefined

### ISSUE THREAD

**Issue by nandafirmans** [TypeStrong/ts-loader#814]
I've just update to webpack 4 and updating ts-loader to 3.5.0 and got error while running webpack watcher

```
TypeError: Cannot read property 'fileTimestamps' of undefined
    at \...\node_modules\ts-loader\dist\watch-run.js:18:39
    at AsyncSeriesHook.eval [as callAsync] (eval at create (\...\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (\...\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Watching._go (\...\node_modules\webpack\lib\Watching.js:40:32)
    at Watching._invalidate (\...\node_modules\webpack\lib\Watching.js:165:9)
    at watcher.compiler.watchFileSystem.watch (\...\node_modules\webpack\lib\Watching.js:136:10)
    at Watchpack.watcher.once (\...\node_modules\webpack\lib\node\NodeWatchFileSystem.js:54:4)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Watchpack.emit (events.js:214:7)
    at Watchpack._onTimeout (\...\node_modules\watchpack\lib\watchpack.js:144:7)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by nandafirmans** [comment]
its work after uninstall and reinstalling ts-loader

**Comment by rbrisita** [comment]
The issue is that ts-loader v3.5.0 does not support webpack v4:
https://github.com/TypeStrong/ts-loader/releases/tag/v4.0.0

To support, update:
npm install --save-dev ts-loader@4.0.0

**Comment by johnnyreilly** [comment]
Given ts-loader is now V6 maybe go for that version 😄
