### ISSUE TITLE
Module build failed: TypeError: Cannot read property getEmitOutput when pass data to ts-loader from the right loader

### ISSUE THREAD

**Issue by liz282907** [TypeStrong/ts-loader#832]
### Expected Behaviour
to support the function of :  require('xx.name.json2')  = get data in the json2 file and inject to the tsx
file . i wrote the json2 loader. and then i have to pass the loader output data to ts-loader. however ,i got the following output: 
```
 error  in ./src/controls-refactor/controls/datetime/index.control.json2

Module build failed: TypeError: Cannot read property 'getEmitOutput' of undefined
    at Object.getEmitOutput (/Users/chenlu/repos/xure/node_modules/ts-loader/dist/instances.js:184:41)
    at getEmit (/Users/chenlu/repos/xure/node_modules/ts-loader/dist/index.js:196:37)
    at successLoader (/Users/chenlu/repos/xure/node_modules/ts-loader/dist/index.js:34:11)
    at Object.loader (/Users/chenlu/repos/xure/node_modules/ts-loader/dist/index.js:21:12)
```

#### the vue.config.js
```
const path = require('path');
module.exports = {
    chainWebpack: config => {
        config.resolve.extensions
            .add('.json2');
        config.module
            .rule('control-json')
            .test(/\.control\.json2$/)
            .use('ts-loader')
                .loader('ts-loader')
                // .options({
                //     transpileOnly: false,
                //     appendTsxSuffixTo: [
                //         '\\.vue$',
                //         '\.json2$'
                //     ]
                // })
                .end()
            .use('json-control-loader')
                .loader('json-control-loader.js')
                .options({
                    emitFile: false
                })
                .end();
        config.resolveLoader.modules.add(path.resolve(__dirname, 'src', 'controls-refactor', 'cores', 'json-control-loader'));
    }
};
```

the actual webpack config:
```
{
        test: /\.control\.json2$/,
        use: [
          /* config.module.rule('control-json').use('ts-loader') */
          {
            loader: 'ts-loader'
          },
          /* config.module.rule('control-json').use('control-json2') */
          {
            loader: 'json-control-loader.js',
            options: {
              emitFile: false
            }
          }
        ]
      }
```

the json2 loader output:
```
function controlLoader(sourceData,sourcemap){
    const source = sourceData.trim();
   if(this.cacheable) this.cacheable();
   const callback = this.async();
   const hocPath = path.resolve(__dirname,'../hoc.tsx');
   this.addDependency(hocPath);
   const self = this;
    
    return loadHocFile(hocPath).catch(callback)
        .then((hocFile)=>{
            const options = getOptions(this);
            const updatedData = injectJsonToHoc(hocFile,source);  // which is actually a tsx file content(string)
            const emitFile = options && options.hasOwnProperty('emitFile')? options.emitFile : true;
            if(!emitFile){
                callback(null, updatedData); // not work when just pass the sourceData
                return;
            }
         .... other code
```

**Comment by johnnyreilly** [comment]
Sorry I don't think this is an issue with ts-loader?  It seems like you're building something - yay!  But it's not obvious that this is an issue with ts-loader....

**Comment by liz282907** [comment]
sorry but the error info is comming from ts-loader?

**Comment by liz282907** [comment]
and i tried to send the tsx content readed from the file and pass it directly to ts-loader (by chaining the previous loader ) . it has the same output error info.

**Comment by johnnyreilly** [comment]
> does the ts-loader only accept only some ext file like json/ts/tsx ?

Pretty much. Though there's this: https://github.com/TypeStrong/ts-loader/blob/master/README.md#appendtssuffixto-regexp-default

Which caters for Vue files but is not specific to them; take a look!
