### ISSUE TITLE
ts-loader emitted no output for .d.ts files while using dynamic import

### ISSUE THREAD

**Issue by ajain17** [TypeStrong/ts-loader#877]
### Expected Behaviour
ts-loader should not try to compile .d.ts files
### Actual Behaviour
```
WARNING in ./ScriptsApp/@types/react-adal.d.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for C:\code\AzureCXP-Eng\src\Applications\AzureCxpWebSite\WebSite\FeedbackSrc\App\ScriptsApp\@types\react-adal.d.ts.
    at makeSourceMapAndFinish (C:\code\AzureCXP-Eng\src\Applications\AzureCxpWebSite\WebSite\FeedbackSrc\App\node_modules\ts-loader\dist\index.js:78:15)
    at successLoader (C:\code\AzureCXP-Eng\src\Applications\AzureCxpWebSite\WebSite\FeedbackSrc\App\node_modules\ts-loader\dist\index.js:68:9)
    at Object.loader (C:\code\AzureCXP-Eng\src\Applications\AzureCxpWebSite\WebSite\FeedbackSrc\App\node_modules\ts-loader\dist\index.js:22:12)
 @ ./ScriptsApp lazy ^\.\/.*$ namespace object ./@types/react-adal.d.ts
 @ ./ScriptsApp/Routes/AppRoutesList.tsx
 @ ./ScriptsApp/Routes/Routes.tsx
 @ ./ScriptsApp/Components/App.tsx
 @ ./ScriptsApp/indexApp.tsx
 @ ./ScriptsApp/index.tsx
 @ multi webpack-hot-middleware/client?reload=true ./ScriptsApp/index.tsx
```
### Steps to Reproduce the Problem
Hi,

I'm having a strange issue with how webpack, tsconfig and .d.ts files are working together.

I've the following project structure:
![image](https://user-images.githubusercontent.com/5581487/49319469-eac57d00-f4b1-11e8-8f4d-b387d14a8ebf.png)

The ScriptsApp contains an @types folder as follows:
![image](https://user-images.githubusercontent.com/5581487/49319473-edc06d80-f4b1-11e8-9397-309cecd6c300.png)

My tsconfig.json is as follows: 
```
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "esnext",
    "lib": [
      "es6",
      "dom",
      "scripthost",
      "es2018",
      "es2018.promise"
    ],
    "jsx": "react",
    "sourceMap": true,
    "outDir": "./.out/",
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "alwaysStrict": true,
    "moduleResolution": "node",
    "typeRoots": ["node_modules/@types", "ScriptsApp/@types"]
  },
  "include": ["./ScriptsApp/**/*.tsx", "./ScriptsApp/**/*.ts", "ScriptsApp/@types"],
  "exclude": ["node_modules"],
  "files": ["ScriptsApp/indexApp.tsx"]
}
```

And this is my webpack config:
 ```
    const path = require("path");
    const webpack = require("webpack");
    const HtmlWebpackPlugin = require("html-webpack-plugin");
    const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
    
    module.exports = {
      mode: "development",
      output: {
        filename: "[name].bundle.[hash].js",
        path: path.join(__dirname, ".out/"),
        chunkFilename: "[name].chunk.js",
        publicPath: "/",
        hotUpdateChunkFilename: ".hot/hot-update.js",
        hotUpdateMainFilename: ".hot/hot-update.json"
      },
      optimization: {
        runtimeChunk: {
          name: "manifest"
        },
        splitChunks: {
          cacheGroups: {
            vendor: {
              test: /[\\/]node_modules[\\/]/,
              name: "vendors",
              priority: -20,
              chunks: "all"
            }
          }
        }
      },
      target: "web",
      devServer: {
        contentBase: ".out/",
        hot: true
      },
      plugins: [
        new webpack.NamedModulesPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new HtmlWebpackPlugin({
          inject: true,
          template: path.join(__dirname, "./index.html")
        }),
    
        new ForkTsCheckerWebpackPlugin({
          checkSyntacticErrors: true,
          tslint: "./tslint.json",
          tslintAutoFix: true,
          tsconfig: "./tsconfig.json",
          async: false,
          reportFiles: ["ScriptsApp/**/*"]
        })
      ],
      module: {
        rules: [
          {
            test: /\.(png|jpg|ico)$/,
            loader: "file-loader",
            options: {
              name: ".img/[name].[ext]?[hash]",
              publicPath: "/"
            }
          },
          {
            test: /\.(woff(2)?|ttf|eot|svg|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "file-loader",
            options: {
              name: ".fonts/[name].[ext]?[hash]",
              publicPath: "/"
            }
          },
          {
            test: /\.(ts|tsx)$/,
            use:"ts-loader"
          },
          {
            test: /\.js$/,
            loader: "source-map-loader"
          },
          {
            test: /\.scss$/,
            use: [
              {
                loader: "style-loader" // creates style nodes from JS strings
              },
              {
                loader: "css-loader",
                options: {
                  sourceMap: true
                }
              },
              {
                loader: "resolve-url-loader"
              },
              {
                loader: "sass-loader",
                options: {
                  sourceMap: true
                }
              }
            ]
          }
        ]
      },
      resolve: {
        extensions: [".js", ".ts", ".tsx", ".scss", ".css", ".png", ".ico", ".json"]
      },
      devtool: "source-map"
    };
```

Now my question:
I'm trying to use dynamic imports as follows:

```
private loadComponentFromPath(path: string) {
    import(`../../ScriptsApp/${path}`).then(component =>
      this.setState({
        component: component.default
      })
    );
  }
```

As soon as I added dynamic import, my build started showing this error for all the .d.ts files inside ScriptsApp/@types folder
	

Working solutions (but I don't understand why they work):
	1. Move @types folder outside the ScriptsApp, or
	2. Not use dynamic imports,
        3. Rename all .d.ts files to .interface.ts

I'm not able to understand why. I'm also new to the entire technology stack so sorry if I'm missing something obvious. Is this expected? Could someone please also this behavior.. Thanks. 

### Location of a Minimal Repository that Demonstrates the Issue.
The code snippet above shows the entire issue

**Comment by johnnyreilly** [comment]
I'd move `@types` outside the ScriptsApp. Closing this as I don't believe this represents an issue with ts-loader

**Comment by ajain17** [comment]
@johnnyreilly  Like I mentioned above, I already have 3 working solutions, but I'd really like to understand why moving @types outside of ScriptsApp works. If you have an explanation, that would really help me. Thank you.

**Comment by johnnyreilly** [comment]
Hi @ajain17 

I'm afraid I don't have an explanation to hand (hence my brief response :smile:)

Here's a good explanation of `types` by the excellent @basarat:

https://basarat.gitbooks.io/typescript/docs/types/@types.html

Quite why moving `@types` fixes the issue I couldn't say. Question: if you run `tsc` in the folder do you get the same issues? If so then it's a question for the TypeScript compiler people themselves :smile:

If you don't then it's worth cracking open our old friend `console.log`, tweaking the ts-loader source and seeing what we can see when you compile.

**Comment by ajain17** [comment]
Thank you. I'll try your suggestions and report back my findings.
