### ISSUE TITLE
Is it mandatory to install this package locally?

### ISSUE THREAD

**Issue by hasankoroglu** [TypeStrong/ts-loader#920]
Do i have to install this package locally? Is it possible to install it globally? I installed it globally but cannot get worked. When i run webpack it gives error like this: 

> ERROR in Entry module not found: Error: Can't resolve 'ts-loader' in 'C:\Users\hasan\Desktop\ts01'

My working folder : https://github.com/hasankoroglu/ts-loader

What am i doing wrong?

**Comment by hasankoroglu** [comment]
I installed it locally but this time it gives error like this:

I think it looks for typescript local node_modules folder. Is there any way to show ts-loader the global node_modules folder?

>ERROR in ./src/app.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Cannot find module 'typescript'
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\hasan\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\hasan\Desktop\ts01\node_modules\ts-loader\dist\utils.js:6:20)
    at Module._compile (C:\Users\hasan\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\hasan\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\hasan\Desktop\ts01\node_modules\ts-loader\dist\after-compile.js:6:17)
    at Module._compile (C:\Users\hasan\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\hasan\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\hasan\Desktop\ts01\node_modules\ts-loader\dist\instances.js:6:25)
    at Module._compile (C:\Users\hasan\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\hasan\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\hasan\Desktop\ts01\node_modules\ts-loader\dist\index.js:5:21)
    at Module._compile (C:\Users\hasan\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)

**Comment by andrewbranch** [comment]
Yes, you should always install project dependencies locally. The only things you should ever install globally are CLI tools that aren't related to any particular project, e.g. `yarn`. Globally installing project dependencies will only bring you pain and suffering, and it looks like Webpack is intentionally preventing you from doing that.
